### ISSUE TITLE
[MAS4.2.1] [Screen Reader-Create a new bot configuration] Screen reader is reading the unnecessary information for “Bot name and End point URL “text fields  

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1744] opened 2019-08-19 11:47 UTC
**Actual Result:**
Screen reader is reading the unnecessary information for “Bot name and End point URL “text fields  
Screen reader is reading as “Bot name asterisk edit required invalid space scan off 

**Expected Result:**
Screen reader should read the proper info for “Bot name and End point URL “text fields  
Example: Screen reader should read as “Bot name asterisk edit field required “

Note: In scan mode narrator focus twice encountered on "Bot name and End point url" and reading as blank.
Please refer the attachment:MAS4.2.1_Blank.zip

**Note:** Issue repro’ing with NVDA also. Please refer the attachment <MAS4.2.1_Create New bot configuration_NVDA.wmv>

**Repro Steps:**
Turn on the narrator 
1.Open the Bot Framework V4 Emulator.
2.Welcome tab screen gets opened
3.Navigate to the Create a new bot configuration and select it
4.Dialog gest opened
5.Navigate to the “Bot name and End point URL” text fields 
6.Observe the issue 

**User Impact:**
Users who rely on screen readers will be affected if the screen reader is reading the inappropriate info for text fields users will be misguide the info for fields 

**Test Environment:**
OS Build: Version 1903(OS Build 18362.239)
Browser: Edge
Application: Bot Framework V4 Emulator
Screen reader: Narrator 

**MAS Reference Link:**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={a12f3779-bdf1-40c2-bbcc-0e314ea94858}](url)
[MAS4.2.1_Create new bot configuration.zip](https://github.com/microsoft/BotFramework-Emulator/files/3515679/MAS4.2.1_Create.new.bot.configuration.zip)
![MAS4 2 1_Create new bot configuration](https://user-images.githubusercontent.com/53518994/63263019-1e953c80-c2a5-11e9-9ca3-67171ea1805b.png)
[MAS4.2.1_Blank.zip](https://github.com/microsoft/BotFramework-Emulator/files/3515730/MAS4.2.1_Blank.zip)

[MAS4.2.1_Create New bot configuration_NVDA.zip](https://github.com/microsoft/BotFramework-Emulator/files/3545964/MAS4.2.1_Create.New.bot.configuration_NVDA.zip)

**Comment by corinagum** [comment] 2019-08-28 23:37
My initial thought here is that the `<TextField>` component (or underlying components) has or have some kind of validation that's checking whether the input is 1) required and 2) valid. My assumption was that this validation was adding aria-labels, which would be the 'required invalid' part of the spoken input name and placeholder.

However, I can't seem to track down the code that validates these inputs. Textfield has a required prop, but that's only adding or removing the red asterisk. The closest I can find is in `botSettingsEditor.tsx`, where there's an error message saying "The bot name is required", but this is not spoken by NVDA when focusing on the inputs. 

Essentially, I think the 'invalid required' is added because the input is marked as required, and the current value is considered invalid, but I can't track down the source code.

@tonyanziano, could you take a look and/or advise? Thank you!

**Comment by tonyanziano** [comment] 2019-09-04 21:12
@corinagum The validation is inherently provided by the `<input>` tag when the `required` attribute is applied. Any `<input>` with a `required` attribute that is currently empty is seen as "invalid" because it is required to be filled out.

If you remove the `required` attribute, NVDA reads the input as:

> "Bot name star edit, blank"

However, if you leave the `required` attribute on, then NVDA reads the input as:

>  "Bot name star edit invalid entry, blank"

We can get rid of the asterisk being read by the screen reader pretty easily, but I'm unclear on what we are supposed to do about the built-in validation.

@Kumar2608 , @awalia13 can we get an example of what the input _should_ say?

**Comment by tonyanziano** [comment] 2019-09-06 21:49
Marking as "by design" because `<input>` tags are narrated this way natively in HTML / on the web.

**Comment by Kumar2608** [comment] 2019-09-19 09:10
As per developer comments We are closing this bug.

**Closed** 2019-09-19 09:11 UTC
Labels: 4.6, A11y-Followup, A11yCT, A11yMAS, A11yMediumImpact, Accessibility, Bug, ByDesign, Fixed, HCL-BotFrameworkEmulator, MAS4.2.1, Severity3
