### ISSUE TITLE
Image routing broken when multiple endpoints are open

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/BotFramework-Emulator#1245] opened 2019-01-18 19:58 UTC
## Version
4.2.1

## Describe the bug
For a bot with multiple endpoints open in multiple tabs in the Emulator, messages with image attachments are sent to the first tab, even when they are generated in a different tab.

## To Reproduce
1. Open and run the [30.asp-mvc-bot](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/30.asp-mvc-bot) locally
1. Attach to it in the Emulator.
1. Close the **welcome** tab, leaving the tab open for **bot1 development** and open a tab for **bot2 development**.
1. Send an image to **bot2**.

   **Error**: no response in the **bot2** tab, the message gets routed to **bot1** and shows up in the first tab.
1. Drag the **bot1** tab over in the UI so that it is now the second tab.
1. Send an image to **bot1**.

   **Error**: no response in the **bot1** tab, the message gets routed to **bot2** and shows up in the first tab.
1. Send an image to **bot2** in the first tab.

   Note that this works as expected.

## Expected behavior
Images get routed to the correct endpoint, the one associated with the tab in which the message was generated.

[bug]

**Comment by tonyanziano** [comment] 2019-01-18 20:01
Thanks for reporting @JonathanFingold . This is a dupe of #1195 .

**Closed by tonyanziano** 2019-01-18 20:01 UTC
