### ISSUE TITLE
Duplicated Activity.Id for RePrompt/Retry in NumberPrompt Dialog.

### ISSUE THREAD

**Issue by eweiguu** [microsoft/BotFramework-Emulator#1888] opened 2019-09-13 03:20 UTC
## Version
What package version of the SDK are you using.
4.5.1
## Describe the bug
Give a clear and concise description of what the bug is.
When NumberPrompt Dialog do re-prompt/retry, it sends the Activity with same Id as the initial prompt activity, The emulator(web-chat) will not rendering the re-prompt/retried activity.

## To Reproduce
1. Create a Dialog with NumberPrompt<int>  with a Text "Please enter a Number" ,
2. Run it thru the emulator, and enter a non-numeric text  for example "XXX".
3. As the input is not a valid number, we expect it emulator will re-prompt it again.
4. However, when you look at the emulator, the chat bot do send the re-prompt activity but it is not rendered, and if you look at the Id of the Activity you will see if as same as the initial one.

## Expected behavior
Give a clear and concise description of what you expected to happen.
Each Activity which bot send to user should have a unique Id.

## Additional context

[bug]

**Comment by cwhitten** [comment] 2019-10-01 02:57
The issue is how the Emulator naively associates an id with an Activity. We will address this in an upcoming release. Thank you for reporting this!

**Comment by stevengum** [comment] 2019-10-03 18:04
@cwhitten should we move this to 4.7?

**Comment by cwhitten** [comment] 2019-10-08 17:27
This is a duplicate of https://github.com/microsoft/BotFramework-Emulator/issues/1684. We will track it to the 4.6 release on that initial issue.

**Comment by tonyanziano** [comment] 2019-10-09 23:12
This is actually a bug in the C# sdk, and is being tracked over on that repository:

https://github.com/microsoft/botbuilder-dotnet/issues/2690

**Closed by tonyanziano** 2019-10-09 23:12 UTC
Labels: Bug, customer-replied-to, customer-reported
