### ISSUE TITLE
Error installing Emulator

### ISSUE THREAD

**Issue by sanjayMT** [Microsoft/BotFramework-Emulator#338] opened 2017-11-06 03:48 UTC
Hi, while trying to install botframework-emulator-Setup-3.5.33.exe on my windows 10 system, It failed to install and getting below error in error log file

CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user-name\AppData\Local\Microsoft\Teams\packages\.betaId'.

heckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user-name\AppData\Local\Microsoft\Teams\packages\RELEASES'.

what could be the issue?

**Comment by th0ger** [comment] 2017-11-06 23:57
I can confirm this error. Looks like access denied to AppData\Local\. Maybe antivirus blocking the install? (McAfee here.)

**Comment by eanders-MS** [comment] 2017-11-08 23:07
Hi @sanjayMT, the log entry in your comment appears to reference a file path for the Teams product (also an Electron app). Do you have MSTeams installed? I'm wondering if this log entry was written by the emulator installation, or if it came from an earlier Teams install. If the log entries have timestamps, do they line up?

**Comment by eanders-MS** [comment] 2017-11-08 23:08
@th0ger, thanks for posting your experience. Did McAfee say why it was flagging the emulator installer?

**Comment by sanjayMT** [comment] 2017-11-09 03:14
Hi @eanders-MS. Yes I have MS Teams installed on my system.

I restarted my system and then I was able to install emulator on my system. Thanks for responding to my query.

**Comment by sanjayMT** [comment] 2017-11-09 03:15
Hi @th0ger, 

No McAfee, but I have Symantec anti-virus installed on my system. I restarted my system and then I was able to install emulator on my system. Thanks for responding to my query.

**Comment by eanders-MS** [comment] 2017-11-09 03:52
We have few solutions here, closing!

**Closed by eanders-MS** 2017-11-09 03:52 UTC
