### ISSUE TITLE
Logging into azure for LUIS gives me {label} message

### ISSUE THREAD

**Issue by tomlm** [Microsoft/BotFramework-Emulator#1487] opened 2019-05-01 23:13 UTC
## Version
4.3.3.57327

## Describe the bug
Logging into azure gives me this error:
![image](https://user-images.githubusercontent.com/17789481/57049239-07fea300-6c2c-11e9-8e90-cfa653f4235c.png)

[bug]

**Comment by justinwilaby** [comment] 2019-05-02 00:10
Closing as duplicate of #1471

**Closed by justinwilaby** 2019-05-02 00:10 UTC
