### ISSUE TITLE
Webchat theming support

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#937] opened 2018-09-27 21:48 UTC
Webchat in the emulator is not themed to match Emulator's current theme setting. 

Filing this work item to track support for theming webchat based on Emulator's theme setting.

**Comment by corinagum** [comment] 2018-10-03 18:30
@mewa1024 Can we sync on this one? :)

**Comment by sgellock** [comment] 2018-10-31 18:58
this would have us pickup the v4 GA version of WebChat and allow us to prove theming works well

**Comment by a-b-r-o-w-n** [comment] 2019-01-14 21:21
I want to be clear about the expectations on this. The current work to update to WebChat v4 (#1219) will include adding dark and high-contrast themes to web chat, but does not yet allow users to provide their own theme. Does that cover this issue or is this more about allowing user's to customize the look of webchat in the emulator?

**Comment by mewa1024** [comment] 2019-01-14 23:02
@a-b-r-o-w-n I believe this issue was intended to support color themes in Emulator: light, dark, and high contrast.

**Comment by a-b-r-o-w-n** [comment] 2019-01-17 23:50
closed in #1206

**Closed by a-b-r-o-w-n** 2019-01-17 23:50 UTC
Labels: 4.3, Approved, P1
