### ISSUE TITLE
A fullstop or dot (.) is getting added at the end of speech input in emulator

### ISSUE THREAD

**Issue by vannela** [microsoft/BotFramework-Emulator#2124] opened 2020-04-06 10:07 UTC
How to remove the the unwanted full-stop or dot (.) being added to speech input in emulator or web-chat hosted on azure.
![Dot Issue In Emulator](https://user-images.githubusercontent.com/7089482/78547321-8ab8b680-781c-11ea-9d37-598a2399b5fa.PNG)

**Comment by tonyanziano** [comment] 2020-04-06 17:32
Hi @vannela ,

This is caused by the Text Normalization feature of the Cognitive Services speech service. [This is configurable through Web Chat](https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/SPEECH.md#text-normalization-options) when embedding the control yourself within your own UI.

However, Web Chat embedding in Azure and in the Emulator do not expose a way for the user to change this option, so the speech service will always normalize text and try to make it appear with the correct punctuation and capitalization.

If you want, we can close this issue and create a feature request to add UI to the Emulator to expose this option. In regards to Web Chat on Azure, we can't do anything about that.

**Comment by vannela** [comment] 2020-04-08 12:02
Thanks for the update, and Yes, this issue can be closed and create a feature request to add UI to the Emulator to expose this option.

**Closed** 2020-04-08 16:02 UTC
Labels: Bug, customer-replied-to, customer-reported
