### ISSUE TITLE
Mic Button not working on local and remote both 

### ISSUE THREAD

**Issue by ktanpatel31** [Microsoft/BotFramework-Emulator#693] opened 2018-07-18 08:01 UTC
**Mic button not working on latest version of emulation.

Kindly provide suggession******

**Comment by tonyanziano** [comment] 2018-07-18 22:40
Hey @ktanpatel31,

This is a known issue with the speech token exchange process (#646) and there is a PR out for a fix #686 .
Thanks

**Comment by compulim** [comment] 2018-07-19 20:45
Merged #686, should have it fixed now.

Will leave this open until it's verified, closing others.

**Comment by vishwacsena** [comment] 2018-07-31 01:29
This needs to be verified on the next V4 Emulator release.

**Comment by vishwacsena** [comment] 2018-09-01 17:56
@compulim - still misting in 4.0.218-nightly

![image](https://user-images.githubusercontent.com/20918136/44948613-9e48a380-add5-11e8-8a56-9d7b4a089660.png)

**Comment by compulim** [comment] 2018-09-14 05:02
Verified fixed in 39389 with PR #841

**Comment by vishwacsena** [comment] 2018-09-14 19:04
![image](https://user-images.githubusercontent.com/20918136/45569956-ffc93300-b815-11e8-8475-4ec260303a83.png)

**Comment by compulim** [comment] 2018-09-14 20:54
@ktanpatel31, the issue is fixed and verified in the latest nightly build.

The speech feature is in private preview, so it is not available for anyone yet. But if you do see it before, you should see it right now.

**Closed by compulim** 2018-09-14 20:54 UTC
Labels: Approved, Next-Iteration, P1, bug, v4
