### ISSUE TITLE
locale setting is not being passed to the bot

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/BotFramework-Emulator#2082] opened 2020-02-17 21:43 UTC
I changed locale setting to "es-ES" in the Emulator settings and the UI changed, but the locale in the message activity is still "en-US":

![image](https://user-images.githubusercontent.com/20775323/74688158-38ec9c00-519c-11ea-9af0-7ada89da65c4.png)

**Comment by tonyanziano** [comment] 2020-02-18 17:00
This might be related to #415

**Comment by turbozapekanka** [comment] 2020-02-18 17:15
Yes this is related and I first discovered this when I noticed welcome message was not translated. I was testing my bot (based on Virtual Assistant) with WebChat and noticed that welcome message is sent in English regardless of the language I specify in WebChat.renderWebChat(). After the first message it switches to Spanish correctly.
Would like to have this fixed or if this is by design, then please suggest a workaround.

**Comment by mdrichardson** [comment] 2020-02-18 17:25
@turbozapekanka What version of Emulator are you using? I'm not able to replicate this in a non-VA bot.

![image](https://user-images.githubusercontent.com/40401643/74761255-8c102e80-5230-11ea-95e2-2c04bb792f8a.png)
![image](https://user-images.githubusercontent.com/40401643/74761283-9b8f7780-5230-11ea-87da-b35e251a2552.png)

**Comment by turbozapekanka** [comment] 2020-02-18 17:43
4.7.0

**Comment by mdrichardson** [comment] 2020-02-18 17:46
@turbozapekanka If you fully close out of Emulator and re-open it, does the problem persist? If so, I'm starting to think it may be specific to that VA bot. I'll spin one up and test it.

**Comment by mdrichardson** [comment] 2020-02-18 17:46
@turbozapekanka If you fully close out of Emulator and re-open it, does the problem persist? If so, I'm starting to think it may be specific to that VA bot. I'll spin one up and test it.

**Comment by turbozapekanka** [comment] 2020-02-18 20:18
It works after I restarted the Emulator!

**Comment by tonyanziano** [comment] 2020-02-18 22:22
Glad to hear that worked @turbozapekanka .

We should still investigate and fix this if it requires a restart for the locale change to take effect; that is not by design.

**Comment by mdrichardson** [comment] 2020-02-18 22:36
@tonyanziano For me, I didn't need to restart for it to take effect. I only recommended it because I've had other odd/sporadic, and unrelated, issues with Emulator that were fixed with a restart.

**Comment by tonyanziano** [comment] 2020-02-18 22:38
@mdrichardson Ah gotcha. Ok well I'll take a look anyways to see if there's anything fishy going on.

**Comment by turbozapekanka** [comment] 2020-02-18 23:05
@mdrichardson I also noticed your screenshot looks a bit different, I don't have this conversationUpdate for example:
![image](https://user-images.githubusercontent.com/20775323/74785824-dfa26c80-5270-11ea-949e-ff260c00beee.png)

**Comment by mdrichardson** [comment] 2020-02-18 23:07
@turbozapekanka I saw that, too. I think sometimes that can happen depending on the timing between starting the conversation and the bot being ready?

**Comment by tonyanziano** [comment] 2020-02-19 23:28
I took a look and could not repro the issue or find anything suspicious in the code that assigns the locale to outgoing activities.

For now I I think it's safe to close this issue, with the workaround being restarting the Emulator as @mdrichardson mentioned.

If there are more reports of settings not saving properly then we can take a deeper dive into the logic behind persisting the app settings.

**Closed by tonyanziano** 2020-02-19 23:28 UTC
Labels: Bot Services, Bug, customer-replied-to, customer-reported
