### ISSUE TITLE
Cannot use Speech when loading bot from url

### ISSUE THREAD

**Issue by corinagum** [microsoft/BotFramework-Emulator#1653] opened 2019-06-24 22:52 UTC
## Version
4.4.2-62022

## Describe the bug
When opening a bot in Emulator, speech works as expected (showing the microphone button on a speech bot) when loaded from a .bot file. However, when I load the same bot WITH appid and password via Bot URL, speech is not enabled and the button (usually airplane) does not change to the microphone icon.

## To Reproduce
1. Deploy a speech bot (please contact me if you need a temporary URL - I can provide)
2. First, create a new bot file with the messaging endpoint, appid, and password
3. Load bot
4. Note that the Microphone icon is shown in the send button, which is expected on this speech bot. 

5. Next, open the same bot via Bot URL, and still provide the appid and password
6. Note that the send icon here is the airplane. There is no way to interact with the bot via stt. Clicking on the icon does not enable the microphone.

## Expected behavior
When I load a speech bot via URL WITH app id and password, the Emulator should allow speech and display the send button as a microphone (instead of paper airplane)

[bug]

**Comment by tonyanziano** [comment] 2019-06-24 23:01
Dupe of #1640

**Closed by tonyanziano** 2019-06-24 23:01 UTC
Labels: Bug

**Comment by corinagum** [comment] 2019-06-25 16:20
Oops, thanks @tonyanziano
