### ISSUE TITLE
Unable to open transcript file

### ISSUE THREAD

**Issue by gps-gagan** [Microsoft/BotFramework-Emulator#704] opened 2018-07-26 15:31 UTC
Hi I am trying to open a transcript file and I am getting the following error:

> Error creating a new conversation for transcript mode:  Error: Error while feeding transcript on disk to conversation: Cannot read property 'role' of undefined
    at Object.<anonymous> (file:///C:/Program%20Files%20(x86)/Bot%20Framework%20Emulator/resources/app…node_modules/@bfemulator/client/build/static/js/main.f356706c.js:1:1992954)
    at Generator.throw (<anonymous>)
    at s (file:///C:/Program%20Files%20(x86)/Bot%20Framework%20Emulator/resources/app…node_modules/@bfemulator/client/build/static/js/main.f356706c.js:1:1988821)
    at <anonymous>
(anonymous) @ main.f356706c.js:1

The transcript file is:

> [
  {
    "conversation": {
      "id": "Dpezwy2Yot8fr7te+9gSQp2OSek="
    },
    "id": "1",
    "timestamp": "2018-07-26T14:03:10.000Z",
    "type": "conversationUpdate",
    "channelId": "chatdown",
    "membersAdded": [
      {
        "id": "feCFNCKOpzAtVMMV7Mm1l+GUZt0=",
        "name": "LulaBot",
        "role": "bot"
      }
    ],
    "membersRemoved": []
  },
  {
    "conversation": {
      "id": "Dpezwy2Yot8fr7te+9gSQp2OSek="
    },
    "id": "2",
    "recipient": {
      "id": "iWYRSfG2L/R91ab+T5ecn1P2GbY=",
      "name": "Joe",
      "role": "user"
    },
    "from": {
      "id": "feCFNCKOpzAtVMMV7Mm1l+GUZt0=",
      "name": "LulaBot",
      "role": "bot"
    },
    "text": "Hi!",
    "timestamp": "2018-07-26T14:03:12.000Z",
    "type": "message",
    "channelId": "chatdown"
  },
  {
    "conversation": {
      "id": "Dpezwy2Yot8fr7te+9gSQp2OSek="
    },
    "id": "3",
    "recipient": {
      "id": "feCFNCKOpzAtVMMV7Mm1l+GUZt0=",
      "name": "LulaBot",
      "role": "bot"
    },
    "from": {
      "id": "iWYRSfG2L/R91ab+T5ecn1P2GbY=",
      "name": "Joe",
      "role": "user"
    },
    "text": "yo!",
    "timestamp": "2018-07-26T14:03:14.000Z",
    "type": "message",
    "channelId": "chatdown"
  },
  {
    "conversation": {
      "id": "Dpezwy2Yot8fr7te+9gSQp2OSek="
    },
    "id": "5",
    "recipient": {
      "id": "iWYRSfG2L/R91ab+T5ecn1P2GbY=",
      "name": "Joe",
      "role": "user"
    },
    "from": {
      "id": "feCFNCKOpzAtVMMV7Mm1l+GUZt0=",
      "name": "LulaBot",
      "role": "bot"
    },
    "timestamp": "2018-07-26T14:03:14.100Z",
    "type": "typing",
    "channelId": "chatdown"
  },
  {
    "conversation": {
      "id": "Dpezwy2Yot8fr7te+9gSQp2OSek="
    },
    "id": "4",
    "recipient": {
      "id": "iWYRSfG2L/R91ab+T5ecn1P2GbY=",
      "name": "Joe",
      "role": "user"
    },
    "from": {
      "id": "feCFNCKOpzAtVMMV7Mm1l+GUZt0=",
      "name": "LulaBot",
      "role": "bot"
    },
    "text": "Greetings!\nWhat would you like to do?\n* update - You can update your account\n* List - You can list your data\n* help - you can get help",
    "timestamp": "2018-07-26T14:03:17.100Z",
    "type": "message",
    "channelId": "chatdown"
  },
  {
    "conversation": {
      "id": "Dpezwy2Yot8fr7te+9gSQp2OSek="
    },
    "id": "6",
    "recipient": {
      "id": "feCFNCKOpzAtVMMV7Mm1l+GUZt0=",
      "name": "LulaBot",
      "role": "bot"
    },
    "from": {
      "id": "iWYRSfG2L/R91ab+T5ecn1P2GbY=",
      "name": "Joe",
      "role": "user"
    },
    "text": "I need the bot framework logo.",
    "timestamp": "2018-07-26T14:03:19.100Z",
    "type": "message",
    "channelId": "chatdown"
  },
  {
    "attachments": [
      {
        "contentType": "image/png",
        "contentUrl": "http://www.garypretty.co.uk/wp-content/uploads/2018/02/botframework-421x410.png"
      },
      {
        "contentType": "image/png",
        "contentUrl": "http://yahoo.com/bot-framework.png"
      }
    ],
    "conversation": {
      "id": "Dpezwy2Yot8fr7te+9gSQp2OSek="
    },
    "id": "7",
    "recipient": {
      "id": "iWYRSfG2L/R91ab+T5ecn1P2GbY=",
      "name": "Joe",
      "role": "user"
    },
    "from": {
      "id": "feCFNCKOpzAtVMMV7Mm1l+GUZt0=",
      "name": "LulaBot",
      "role": "bot"
    },
    "text": "Here you go.",
    "timestamp": "2018-07-26T14:03:21.100Z",
    "type": "message",
    "channelId": "chatdown",
    "attachmentLayout": "carousel"
  },
  {
    "conversation": {
      "id": "Dpezwy2Yot8fr7te+9gSQp2OSek="
    },
    "id": "8",
    "recipient": {
      "id": "feCFNCKOpzAtVMMV7Mm1l+GUZt0=",
      "name": "LulaBot",
      "role": "bot"
    },
    "from": {
      "id": "iWYRSfG2L/R91ab+T5ecn1P2GbY=",
      "name": "Joe",
      "role": "user"
    },
    "text": "thanks",
    "timestamp": "2018-07-26T14:03:23.100Z",
    "type": "message",
    "channelId": "chatdown"
  },
  {
    "conversation": {
      "id": "Dpezwy2Yot8fr7te+9gSQp2OSek="
    },
    "id": "9",
    "recipient": {
      "id": "iWYRSfG2L/R91ab+T5ecn1P2GbY=",
      "name": "Joe",
      "role": "user"
    },
    "from": {
      "id": "feCFNCKOpzAtVMMV7Mm1l+GUZt0=",
      "name": "LulaBot",
      "role": "bot"
    },
    "text": "Here's a form for you",
    "timestamp": "2018-07-26T14:03:25.100Z",
    "type": "message",
    "channelId": "chatdown"
  },
  {
    "attachments": [
      {
        "contentType": "application/vnd.microsoft.card.signin",
        "content": {
          "buttons": [
            {
              "title": "sign-in",
              "type": "imBack",
              "value": "sign-in"
            }
          ],
          "title": "botframework sign-in card"
        }
      }
    ],
    "conversation": {
      "id": "Dpezwy2Yot8fr7te+9gSQp2OSek="
    },
    "id": "10",
    "recipient": {
      "id": "iWYRSfG2L/R91ab+T5ecn1P2GbY=",
      "name": "Joe",
      "role": "user"
    },
    "from": {
      "id": "feCFNCKOpzAtVMMV7Mm1l+GUZt0=",
      "name": "LulaBot",
      "role": "bot"
    },
    "text": "The Sign-In card is a card representing a request to sign in the user.",
    "timestamp": "2018-07-26T14:03:27.100Z",
    "type": "message",
    "channelId": "chatdown"
  }
]

**Comment by tonyanziano** [comment] 2018-07-26 21:40
Hello @gps-gagan ,

This is currently a known issue, and is being tracked here #675.

The issue is due to the activities of `type: conversationUpdate` that are generated when members are added or removed from the conversation (see `membersAdded` & `membersRemoved` properties). They are not yet supported by transcript mode.

**Comment by vishwacsena** [comment] 2018-08-01 01:00
Closing this since this is pending enhancement to the emulator that we are actively working on.

**Closed by vishwacsena** 2018-08-01 01:00 UTC

**Comment by corinagum** [comment] 2018-09-27 16:34
#931
