### ISSUE TITLE
Unable to upload attachment POST 400 Bad Request

### ISSUE THREAD

**Issue by faresayyad** [Microsoft/BotFramework-Emulator#2477] opened 2024-12-23 21:12 UTC
I am trying to test the attachment handling functionality in one of my projects, but I am unable to upload attachments.
when I try to select a file I got: 
send failed  POST 400 directline/conversations/<conversationId>/upload

In the Network tab of developer tools: 
**Response:**
{"error":{"code":"ServiceError","message":"path is not defined"}}
**Headers:**
Request URL:
http://localhost:52635/v3/directline/conversations/d2e67ac0-c171-11ef-8f15-090b3bf0e8cf%7Clivechat/upload?userId=db7a6d4d-a457-4141-ac0c-eb97e4f16dac
Request Method:
POST
Status Code:
400 Bad Request
Remote Address:
[::1]:52635
Referrer Policy:
strict-origin-when-cross-origin

![Image](https://github.com/user-attachments/assets/2b575af3-f383-4850-9ece-db90f9344a92)

**Comment by rido-min** [comment] 2024-12-26 18:53
seems like a dupe of https://github.com/microsoft/BotFramework-Emulator/issues/2471

**Comment by dmvtech** [comment] 2024-12-26 19:25
Closing as duplicate.

**Closed as completed by dmvtech** 2024-12-26 19:25 UTC
