### ISSUE TITLE
Adaptive Card Markdown not working on v3

### ISSUE THREAD

**Issue by arashberlin** [Microsoft/BotFramework-Emulator#508] opened 2018-05-16 11:27 UTC
Hi there,

after wasting time to figure it out why Markdown in Adaptive Card is not rendering. [Found it here](https://github.com/Microsoft/AdaptiveCards/issues/1421)

there is no longer bundle a default markdown implementation in the JavaScript renderer.  

In web chat I put the markdown-it.js before my chatbot.js and all good.
<script type="text/javascript" src="https://unpkg.com/markdown-it/dist/markdown-it.js"></script>

But how do I manage to set this up for the emulator?  I start to use the V4 alpha edition.

So these are breaking changes, and there is no information about it.

Related to : [https://github.com/Microsoft/BotFramework-WebChat/issues/949](https://github.com/Microsoft/BotFramework-WebChat/issues/949)  & [https://github.com/Microsoft/BotFramework-WebChat/issues/972](https://github.com/Microsoft/BotFramework-WebChat/issues/972)

**Comment by emadelwany** [comment] 2018-05-17 21:44
This is by design, web chat doesn't support MD in cards.

**Comment by arashberlin** [comment] 2018-05-18 06:25
Ok, but how is it possible to test the results in the emulator? It was possible in the past?

In the web chat I can add a MD JavaScript library before chatbot.js and MD is OK.

How to proceed it with the emulator? 
Or emulator is not for custom design.
Do I need to compile my own emulator version with MD JavaScript library?

Thanks for helping me with this issue.

**Comment by emadelwany** [comment] 2018-05-18 06:41
@compulim can you please advise?

**Comment by CodeDragoon** [comment] 2018-07-03 07:07
I am stuck  with the same problem

**Comment by compulim** [comment] 2018-07-03 08:31
Adaptive Cards team decided to pull out the Markdown-It in the bundle at Adaptive Cards 1.0 (adopted in Web Chat 0.12.0). In order to use Markdown in Adaptive Cards in Web Chat, one have to bring their own Markdown-It engine via `window.markdownit` (i.e. from their [CDN](https://github.com/markdown-it/markdown-it#install)).

What's more, our legacy cards (hero card, thumbnail card, receipt card) are converted to Adaptive Cards. So Markdown inside all cards are not rendered properly.

But since we bundled Markdown-It into Web Chat, we will now expose Markdown-It as `window.markdownit` in PR #1034.

**Comment by compulim** [comment] 2018-08-16 06:17
Since we have #710 also on the same issue. I am changing this one #508 for v3, and #710 for v4.

**Comment by compulim** [comment] 2018-08-27 18:43
We are sunsetting v3 and moving to v4. Closing this bug.

**Closed by compulim** 2018-08-27 18:43 UTC
Labels: bug, cards

**Comment by compulim** [comment] 2018-08-27 18:44
In case someone want to fix it:

- Bump `botframework-webchat` to `>=0.14.1`
- Verify all functionalities
