### ISSUE TITLE
[MAS1.4.13] [Keyboard Navigation-Live Chat] When the user hovered on “Split editor, Presentation mode” tooltip controls, tooltip gets disappears  

### ISSUE THREAD

**Issue by awalia13** [microsoft/BotFramework-Emulator#1720] opened 2019-08-12 11:02 UTC
Actual Result:
When the user hovered on “Split editor, Presentation mode” tool tip controls, tool tip gets disappears which present in the Live chat tab screen 

Expected Result:
When the user hovered on “Split editor, Presentation mode” tooltip controls, tooltip should not disappear 

Note: Issue repro throughout the application wherever tooltip controls are present. 
Same issue repro for below path 
Navigate to the Open bot ->Select the Open bot control->Open bot dialog
1.browse control.
Navigate to the Open bot ->Select the Open bot control->Open bot dialog ->Connect the bot 
1.File upload button 2.Send button 
Bot Explorer->Endpoint->+symbol:
1.End point url 2.Name .
Welcome Bot Framework Emulator ->Create new bot configuration
1.Bot Name 2.End Point URL.

Repro Steps:
1. Open the Bot Framework V4 Emulator.
2. Navigate to the Welcome tab screen 
3. Navigate to the Create new bot configuration 
4. Navigate to the Save and connect control and select it 
5.Live chat tab screen gets appeared 
6.Navigate to the “Split editor, Presentation mode” tooltip controls hovered on it 
7.Observe the issue.

User Impact:
End user who rely on AT will not be able to get this hover information if the information is disappearing when we try to navigate on it .

Test Environment:
OS Build: Version 1903(OS Build 18362.239)
Browser: Edge
Application: Bot Framework V4 Emulator

MAS Reference Link:
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/Doc.aspx?sourcedoc=%7B60121EB2-D1C5-4525-931F-322A940799EF%7D&file=MAS%201.4.13%20%E2%80%93%20Content%20on%20Hover%20or%20Focus.docx&action=default&mobileredirect=true&cid=c368d1cb-2c0f-4858-89f9-67ffdf2ccd92](url)
[MAS1.4.13_Live chat.zip](https://github.com/microsoft/BotFramework-Emulator/files/3491993/MAS1.4.13_Live.chat.zip)

**Comment by corinagum** [comment] 2019-08-29 22:03
Duplicate of #1715

**Closed by corinagum** 2019-08-29 22:03 UTC
Labels: A11yCT, A11yMAS, A11yMediumImpact, A11yWCAG2.1, Accessibility, Bug, HCL-BotFrameworkEmulator, MAS1.4.13, Severity3
