### ISSUE TITLE
"Open Bot" button disabled after cancelling entry of Bot Secret

### ISSUE THREAD

**Issue by nyxsys** [Microsoft/BotFramework-Emulator#875] opened 2018-09-14 19:08 UTC
After clicking dismiss on this screen 

<img width="232" alt="pw" src="https://user-images.githubusercontent.com/6576516/45570229-c218da00-b816-11e8-8059-7a91b4a18433.PNG">

I am sent back to the main bot page, and the button in the following screenshot no longer works

<img width="210" alt="disabled_button" src="https://user-images.githubusercontent.com/6576516/45570171-97c71c80-b816-11e8-99b3-cb2ec71bc66d.PNG">

This does not occur with the other "Open Bot" button, only the one in the sidebar.

**Comment by vishwacsena** [comment] 2018-09-14 19:38
dupe of #797

**Closed by vishwacsena** 2018-09-14 19:38 UTC
