### ISSUE TITLE
Marked down base64 encoded images not getting rendered

### ISSUE THREAD

**Issue by hpksp** [microsoft/BotFramework-Emulator#1401] opened 2019-03-28 08:34 UTC
## Version
v4.3.3

## Describe the bug
Marked down base64 encoded images not getting rendered. Instead shows the image caption. This approach works perfectly on v3 emulator, web chat, skype, slack and ms teams. 

## Screenshots
![em bug](https://user-images.githubusercontent.com/4414397/55141860-59b19a80-5161-11e9-8e0f-815611506ebf.png)

**Comment by denscollo** [comment] 2019-04-12 20:41
We reviewed the code and after running some tests using WebChat alone on HTML, Azure Portal and React Web Apps, we came to the conclusion that the issue is not located on Emulator itself, but on the ReactWebChat library of BotFramework-WebChat. 

We created an issue for this on the corresponding repository [ISSUE#1896](https://github.com/Microsoft/BotFramework-WebChat/issues/1896)

**Comment by denscollo** [comment] 2019-06-10 21:21
We fixed this issue on [#2067](https://github.com/microsoft/BotFramework-WebChat/pull/2067)

**Comment by tonyanziano** [comment] 2019-06-10 21:23
Great! Thanks @denscollo.

So we just need to bump the embedded Web Chat version within Emulator and verify that the fix propagates to Emulator.

**Comment by denscollo** [comment] 2019-06-10 21:29
@tonyanziano We ran some tests using a local version of WebChat with this fix and it worked perfectly on Emulator. Let us know if something doesn't work properly and we'll check it!

**Comment by tonyanziano** [comment] 2019-06-27 21:02
This will be fixed once the Emulator bumps its Web Chat dependency to the next stable release.

**Closed by tonyanziano** 2019-06-27 21:02 UTC
Labels: Bug, P1, Southworks
