### ISSUE TITLE
Adaptive Card ColumnSet does not render on Bot Emulator v4

### ISSUE THREAD

**Issue by abhilashr1** [Microsoft/BotFramework-Emulator#1197] opened 2018-12-27 12:36 UTC
## Version
4.2.1

## Describe the bug
Adaptive Cards of version 1.1 do not render on Bot emulator. However, this works fine on webchat (preview enabled)

## To Reproduce
Nuget package and version being used: 

`  <package id="AdaptiveCards" version="1.1.0" targetFramework="net46" />`

## Code Used:
```
      var PhoneList = new List<AdaptiveElement>();
            for (int i = 0; i <= 6; i++)
            {
                var tmp = new AdaptiveTextBlock()
                {
                    Text = "Test",
                    Wrap = true
                };
                PhoneList.Add(tmp);
            }

            // Headers
            card.Body.Add(new AdaptiveColumnSet()
            {
                Columns = new List<AdaptiveColumn>()
            {
                new AdaptiveColumn()
                {
                        Items = PhoneList ,
                        Separator = true,
                },
                new AdaptiveColumn()
                {
                        Items = PhoneList ,
                        Separator = true

                },
                new AdaptiveColumn()
                {
                        Items = PhoneList,
                        Separator = true

                },
                new AdaptiveColumn()
                {
                        Items = PhoneList ,
                        Separator = true

                },
            }
            });

            Attachment attachment = new Attachment()
            {
                ContentType = AdaptiveCard.ContentType,
                Content = card
            };
            var replyMessage = context.MakeMessage();
            replyMessage.Attachments = new List<Attachment> { attachment };
            await context.PostAsync(replyMessage);
```

## Expected behavior / Screenshots
It works fine on webchat:
![image](https://user-images.githubusercontent.com/10576869/50480357-7bd03b00-0a01-11e9-83f9-198c7093259f.png)

*On Emulator:*
![image](https://user-images.githubusercontent.com/10576869/50480369-930f2880-0a01-11e9-9d85-ed4cf2684b7b.png)

## Additional context
This is what the activity looks like in emulator

```
{
  "attachments": [
    {
      "content": {
        "actions": [],
        "body": [
          {
            "columns": [
              {
                "height": "auto",
                "items": [
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  }
                ],
                "separator": true,
                "type": "Column"
              },
              {
                "height": "auto",
                "items": [
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  }
                ],
                "separator": true,
                "type": "Column"
              },
              {
                "height": "auto",
                "items": [
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  }
                ],
                "separator": true,
                "type": "Column"
              },
              {
                "height": "auto",
                "items": [
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  },
                  {
                    "height": "auto",
                    "text": "Test",
                    "type": "TextBlock",
                    "wrap": true
                  }
                ],
                "separator": true,
                "type": "Column"
              }
            ],
            "height": "auto",
            "type": "ColumnSet"
          }
        ],
        "height": "auto",
        "type": "AdaptiveCard",
        "version": "1.1"
      },
      "contentType": "application/vnd.microsoft.card.adaptive"
    }
  ],
  "channelId": "emulator",
  "conversation": {
    "id": "xxx|livechat"
  },
  "entities": [],
  "from": {
    "id": "xxx",
    "name": "Bot"
  },
  "id": "xxx",
  "localTimestamp": "2018-12-27T18:04:39+05:30",
  "locale": "",
  "recipient": {
    "id": "xxx",
    "role": "user"
  },
  "replyToId": "xxx",
  "serviceUrl": "http://localhost:51616",
  "text": "",
  "timestamp": "2018-12-27T12:34:39.799Z",
  "type": "message"
}
```

[bug]

**Comment by tonyanziano** [comment] 2018-12-27 22:30
@abhilashr1 We currently have an older version of WebChat mounted within the emulator which I believe to be the cause of the problem. We are working on mounting the new V4 version of WebChat, which hopefully will resolve your issue.

In the interim, I'll investigate a little deeper into this issue and confirm that it will be fixed with the newer version of WebChat.

**Comment by compulim** [comment] 2018-12-27 23:47
## Note to investigators

- Check if the Adaptive Card JSON is working on Web Chat v3 (with AC 1.0)
   - If yes, investigate further to see why it is breaking
   - If no, figure out our AC compat/bump story

**Comment by corinagum** [comment] 2019-01-03 00:42
Progress for updating Web Chat on Emulator to v4 can be tracked [here](https://github.com/Microsoft/BotFramework-Emulator/issues/1206).

**Comment by tonyanziano** [comment] 2019-04-12 19:52
Verified as fixed in the latest version:

![image](https://user-images.githubusercontent.com/3452012/56062601-c6ac5f00-5d21-11e9-9544-3edd53f37696.png)

**Closed by tonyanziano** 2019-04-12 19:52 UTC
Labels: Bug, WebChat

**Comment by HeisenbergMarc** [comment] 2019-07-15 09:06
I have a related bug:

# Version
4.2.1

# Describe the bug
Adaptive Cards json of version 1.1  do not render on Bot emulator. But it works fine on webchat.

# Code Used:
This is my Adaptive Card:
```
{
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "items": [
        {
          "type": "TextBlock",
          "text": "Create Ticket",
          "size": "ExtraLarge"
        },
        {
          "type": "TextBlock",
          "text": "You already entered this information"
        },
        {
          "type": "Container",
          "items": [
            {
              "type": "FactSet",
              "facts": [
              ]
            },
            {
              "type": "TextBlock",
              "text": "What's your problem?*"
            },
            {
              "type": "Input.Text",
              "placeholder": "Describe your problem",
              "isMultiline": true,
              "id": "input-problem"
            },
            {
              "type": "TextBlock",
              "text": "Do you have an error-code?"
            },
            {
              "type": "Input.Text",
              "placeholder": "Paste in your error-code if you have one",
              "isMultiline": true,
              "id": "input-errorcode"
            }
          ]
        }
      ],
      "type": "Container"
    },
    {
      "type": "Container",
      "items": [
        {
          "type": "FactSet",
          "facts": [
            {
              "title": "Submitted By",
              "value": "UserNameHere"
            },
            {
              "title": "Submitted On",
              "value": "DateHere"
            }
          ]
        }
      ]
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Submit",
      "data": {
        "action": "submit"
      },
      "style": "positive",
      "id": "submit"
    },
    {
      "type": "Action.Submit",
      "title": "Cancel",
      "data": {
        "action": "cancel"
      },
      "style": "destructive",
      "id": "cancel"
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "lang": "en"
}
```

Im modifying my json manually in an loop:
```
public static Activity GetAdaptiveTicketCard(string username, List<Question> questions)
        {

            var json = File.ReadAllText(_cards[2]);
            json = json.Replace("UserNameHere", username);

            DateTime thisDay = DateTime.Today;
            json = json.Replace("DateHere", thisDay.ToString("d"));

            dynamic dynamicObj = JsonConvert.DeserializeObject(json);

            for (int i = 1; i <= questions.Count; i++)
            {
                dynamic dynQuestion = new JObject();
                dynamicObj.body[0].items[2].items[0].facts.Add(dynQuestion);
                dynQuestion.value = questions[i - 1].String;
                dynQuestion.title = i;
                dynamicObj.body[0].items[2].items[0].facts[i-1] = dynQuestion;
            }

            var adaptiveCardAttachment = new Attachment()
            {
                ContentType = "application/vnd.microsoft.card.adaptive",
                Content = dynamicObj,
            };
            var chatActivity = MessageFactory.Attachment(adaptiveCardAttachment);

            return (Activity)chatActivity;
        }
```

# Expected behavior / Screenshots
It works fine on webchat:
![11](https://user-images.githubusercontent.com/25687814/61205326-110df500-a6f0-11e9-8d79-e5a1d3515afd.PNG)


On Emulator:
![22](https://user-images.githubusercontent.com/25687814/61205349-19663000-a6f0-11e9-8d6c-893ff1016d4d.PNG)


Additional context
activity in the emulator:
```
{
  "attachmentLayout": "list",
  "attachments": [
    {
      "content": {
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "actions": [
          {
            "data": {
              "action": "submit"
            },
            "id": "submit",
            "style": "positive",
            "title": "Submit",
            "type": "Action.Submit"
          },
          {
            "data": {
              "action": "cancel"
            },
            "id": "cancel",
            "style": "destructive",
            "title": "Cancel",
            "type": "Action.Submit"
          }
        ],
        "body": [
          {
            "items": [
              {
                "size": "ExtraLarge",
                "text": "Create Ticket",
                "type": "TextBlock"
              },
              {
                "text": "You already entered this information",
                "type": "TextBlock"
              },
              {
                "items": [
                  {
                    "facts": [
                      {
                        "title": 1,
                        "value": "start_tree"
                      },
                      {
                        "title": 2,
                        "value": "Services"
                      }
                    ],
                    "type": "FactSet"
                  },
                  {
                    "text": "What's your problem?*",
                    "type": "TextBlock"
                  },
                  {
                    "id": "input-problem",
                    "inlineAction": {
                      "type": "Action.Submit"
                    },
                    "isMultiline": true,
                    "placeholder": "Describe your problem",
                    "type": "Input.Text"
                  },
                  {
                    "text": "Do you have an error-code?",
                    "type": "TextBlock"
                  },
                  {
                    "id": "input-errorcode",
                    "isMultiline": true,
                    "placeholder": "Paste in your error-code if you have one",
                    "type": "Input.Text"
                  }
                ],
                "type": "Container"
              }
            ],
            "type": "Container"
          },
          {
            "items": [
              {
                "facts": [
                  {
                    "title": "Submitted By",
                    "value": "User"
                  },
                  {
                    "title": "Submitted On",
                    "value": "15.07.2019"
                  }
                ],
                "type": "FactSet"
              }
            ],
            "type": "Container"
          }
        ],
        "lang": "en",
        "type": "AdaptiveCard",
        "version": "1.0"
      },
      "contentType": "application/vnd.microsoft.card.adaptive"
    }
  ],
  "channelId": "emulator",
  "conversation": {
    "id": "bfb12d71-a6d7-11e9-abbd-57fd0e7914c4|livechat"
  },
  "entities": [],
  "from": {
    "id": "38a06130-85cf-11e9-9c20-4302a4226584",
    "name": "Bot",
    "role": "bot"
  },
  "id": "cecad6d0-a6d7-11e9-a2d2-5523b2feb1cc",
  "inputHint": "acceptingInput",
  "localTimestamp": "2019-07-15T10:09:02+02:00",
  "locale": "en-US",
  "recipient": {
    "id": "6acb643c-92ca-434b-901f-a4e3d153f1be",
    "role": "user"
  },
  "replyToId": "ceb3a550-a6d7-11e9-a2d2-5523b2feb1cc",
  "serviceUrl": "http://localhost:52305",
  "timestamp": "2019-07-15T08:09:02.909Z",
  "type": "message"
}
```
