### ISSUE TITLE
Task Cancelled when calling GetUserTokenAsync using Emulator

### ISSUE THREAD

**Issue by Crazedpeanut** [Microsoft/BotFramework-Emulator#1249] opened 2019-01-23 21:25 UTC
## Version
4.2.1

## Describe the bug
I expect to retrieve a mock user access token when calling GetUserTokenAsync, using the emulator. 
I actually get an exception with message:

{System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request. ---> System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)}

## To Reproduce
1. Open Bot Framework Emulator 4.2.1
2. Call GetUserTokenAsync()
3. Wait around 30 seconds

## Expected behavior
I expected a mock user token to be retrieved

[bug]

**Comment by drub0y** [comment] 2019-02-04 23:10
For the record, this is the behavior in .NET that is caused by #1212. So you can probably link this issue to that one and confirm it's gone once that bug is fixed.

**Comment by tonyanziano** [comment] 2019-04-12 18:42
This was caused by #1212  which was fixed and related to #1268 which was also fixed after a lengthy investigation. Closing this.

**Closed by tonyanziano** 2019-04-12 18:42 UTC
