### ISSUE TITLE
Bot Emulator not trusted by Microsoft

### ISSUE THREAD

**Issue by mattsmall1972** [microsoft/BotFramework-Emulator#2346] opened 2021-11-30 20:12 UTC
## Version
4.14.1

## Describe the bug
I am developing a Microsoft-internal bot using the Microsoft tenant with authentication.  When signing in using the Emulator, a message appears that says:  

You can't get there from here
This application contains sensitive information and can only be accessed from:
Devices or client applications that meet Microsoft management compliance policy.
The current browser is not supported, please use Microsoft Edge, Internet Explorer or Chrome to access this application.

## To Reproduce
1. Create bot in internal Microsoft tenant
2. Set up BotAuthenticationMSGraph sample
3. Log into the bot

## Expected behavior
Bot is trusted by the Microsoft IT department and is usable for log in.

## Screenshots
![image](https://user-images.githubusercontent.com/28765633/144120727-b5a38d99-e9bc-4ebc-9308-2ae4a99a0fb4.png)

[bug]

**Comment by axelsrz** [comment] 2021-12-01 19:13
Hello @tonyanziano, could you take a look at this?

**Comment by tonyanziano** [comment] 2021-12-01 19:28
This is a dupe of #2346 and you can find the explanation for the error [here](https://github.com/microsoft/BotFramework-Emulator/issues/2253#issuecomment-841508903).

In short, sign-in was broken via a company-wide policy change and fixing it requires the implementation of an internal authentication library that the Emulator currently does not have the dev funding for.

**Closed by tonyanziano** 2021-12-01 19:28 UTC
Labels: Bug, customer-reported, Bot Services

**Comment by mattsmall1972** [comment] 2021-12-01 21:07
Thanks Tony.  I'd seen that but didn't scroll down far enough to realize that it was the same one.

**Comment by sambathrajv** [comment] 2024-02-17 02:53
This issue still exists. For those who are facing this problem, debug your bot using the steps https://learn.microsoft.com/en-us/azure/bot-service/bot-service-debug-channel-ngrok?view=azure-bot-service-4.0. Sign in steps can be verified in this way.
