### ISSUE TITLE
Responsive design for the LUIS and QnA extensions

### ISSUE THREAD

**Issue by emadelwany** [Microsoft/BotFramework-Emulator#501] opened 2018-05-15 22:57 UTC

**Comment by vishwacsena** [comment] 2018-08-13 19:17
This appears to be dupe of #518 - @mewa1024  - can you check/ confirm and close as appropriate?

**Comment by mewa1024** [comment] 2018-08-13 21:34
Yes, this is a dupe. Closing.

**Closed by mewa1024** 2018-08-13 21:34 UTC
Labels: design, v4
