### ISSUE TITLE
Connect to a bot running on localhost

### ISSUE THREAD

**Issue by chuksogbolime** [Microsoft/BotFramework-Emulator#51] opened 2016-12-23 12:11 UTC
I cannot seem to connect to my application running on localhost from visual studio using the Bot Emulator(v3.5). I keep getting the error "connect ECONNREFUSED" even when the application is started.

Can anyone help?

**Comment by eanders-MS** [comment] 2016-12-23 21:19
Hi @chuksogbolime, I can help troubleshoot. A few questions:
- Do you know which port is your localhost bot listening on?
- What are you specifying for your bot endpoint in the emulator? Is it something like `http://localhost:3978/api/messages`?

**Comment by abhishan** [comment] 2016-12-26 21:16
I have the same issue.
Here is the Log:
[02:40:15] Application is up to date. 
[02:40:15] Emulator listening on http://[::]:54485 
[02:40:43] -> POST connect ECONNREFUSED 127.0.0.1:3978 

The bot endpoint is: http://localhost:3978/api/messages

I have tried this with and without MSA. Also turned off all firewalls.

**Comment by abhishan** [comment] 2016-12-26 21:37
**Observation:**
When I use the VS template and run the bot, the emulator doesn't work.
But, when the build and run the Echo Bot sample, the emulator works.

Log:
[02:56:40] Application is up to date. 
[02:56:40] Emulator listening on http://[::]:55067 
[02:59:18] -> POST connect ECONNREFUSED 127.0.0.1:3978
[03:02:43] <- POST 200 Reply[message] Welcome User  /* Connected to echobot running on port 53318*/
[03:02:44] <- POST 200 Reply[message] Welcome User! 
[03:02:44] -> POST 202 [conversationUpdate] 
[03:03:17] <- POST 200 Reply[message] 1: You said hello 
[03:03:18] -> POST 202 [message] hello

**Comment by chuksogbolime** [comment] 2016-12-27 14:28
I have been able to get around this issue. I think the problem was with the visual studio template version I installed. I have updated it to 3.4.0 and used it to build a sample Bot Application and it works fine.

**Comment by abhishan** [comment] 2016-12-27 14:58
@chuksogbolime Can you please share the link/ resource from where I can get the 3.4.0 template. Thanks!
~abhishan

**Comment by chuksogbolime** [comment] 2016-12-28 09:14
@abhishan, you will need to delete the template file placed in the c# template directory as directed by the documentation and then install the template (Bot_Application) directly from visual studio created by Yowko Tsai.

**Comment by eanders-MS** [comment] 2017-01-03 17:42
This issue appears to be resolved. Closing it now. If I'm incorrect, please let me know and I will reopen.

**Closed by eanders-MS** 2017-01-03 17:42 UTC

**Comment by adrobson** [comment] 2017-03-12 15:17
I am having the same problem with version 3.5 of the bot builder framework. Is there another version of the template? I create a project from scratch using 3.5 of the framework and used the controller from the template but I still have the same issue - econnrefused

**Comment by we-CONECT-Joe** [comment] 2017-04-02 11:17
same here!
- Downloaded the latest template & VS 2017
- put the templates in the proper folder
- created new project from template
- built it for dependencies
- registered bot online
- rebuild bot with new keys
- starting up latest emulator
- receiving: "POST connect ECONNREFUSED 127.0.0.1:3978 "

**Comment by torrtuga** [comment] 2017-08-09 07:36
I followed the instruction over here : https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-quickstart
But it didn't work. Its giving me the error : POST connect ECONNREFUSED 127.0.0.1:3978
URL is http://localhost:3978/api/messages

This is happening in the botframework-emulator. Have used ngrok aslo. 
Any idea why this is happening?

**Comment by ClydeDz** [comment] 2017-08-21 12:03
Had faced a couple of issues while trying to get the bot emulator connect to my bot application on localhost but finally was able to make a connection. Here is how -

1. Created a new project in VS 2015 from a new 'bot application' [template](https://marketplace.visualstudio.com/items?itemName=YowDS.BotApplication).
2. Clear the MicrosoftAppId and MicrosoftAppPassword values from the web config.
3. Ensure that you're project runs on the URL http://localhost:3978/ (test in the browser to verify this). Keep the app running (assuming its on IIS Express). As per [this article](https://docs.microsoft.com/en-us/bot-framework/debug-bots-emulator#localhost), the **URL has to be** localhost:3978.
4. Open bot framework emulator. 
5. Connect to the URL endpoint http://localhost:3978/api/messages where 3978 is the same port that we just set for our web application and /api/messages is the POST endpoint for our bot as per the template we downloaded.
6. Keep the values for 'Microsoft App Id'  and 'Microsoft App Password' blank. Locale is set to en-US by default (you cannot set this blank).
7. You should be able to connect and see 200 [conversationUpdate] messages exchanged at the bottom-right of the bot emulator. 

**Note:** As per the installed template, I was using Microsoft.Bot.Builder version 3.0.0 and this produced a warning message in the bot emulator **but it still worked**. As per the recommendation (>=3.5.0), I updated it to 3.5.1.

You can also add breakpoints in your code and debug the code using this process.

Hope this helps!

Thanks,
Clyde

**Comment by horibu** [comment] 2018-02-28 04:18
Hi there,

I am facing the same issue with the emulator as the people above. The problem is not really solved..one can only find some hints regarding Visual Studio users and templates.. I am using a Mac with Sublime Text as Editor and installed Emulator Version 3.5 . Ae there any Node.JS templates that can or should be installed? I followed the tutorialsstep by step,  but I am not advancing at all because of this issue.

The error I get:
 POST connect ECONNREFUSED 127.0.0.1:3978

What is striking to me, is the fact that I am reaching for the URL => http://localhost:3978/api/messages, but in the emulator the error says: 127.0.0.1:3978..so no localhost:3978.

Where can the port of the emulator be changed?? And pls for Sublime Editor and not Visual Studio!!


Thanks!!
