### ISSUE TITLE
Emulator UI: navbar "Resources" icon should toggle the pane open/closed

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#831] opened 2018-09-06 01:04 UTC
Build 4.0.262-nightly

Clicking on the resources does not toggle the pan open/closed, but it should. 

Repro: open Bot Explorer pane. Click Resources icon to switch to Resource pane. Click the Resources icon. The pane should close.

**Comment by vishwacsena** [comment] 2018-09-06 21:04
Dupe of #826

**Closed by vishwacsena** 2018-09-06 21:04 UTC
Labels: bug
