### ISSUE TITLE
Emulator 4.14.1 does not prompt for user properly after having logged out

### ISSUE THREAD

**Issue by mattsmall1972** [microsoft/BotFramework-Emulator#2345] opened 2021-11-30 18:54 UTC
## Version
4.14.1

## Describe the bug
I am testing the BotAuthenitcationMSGraph sample.  I have it working and need to change the user for other testing.  I have restarted the sample as well as the emulator.  I have also logged out of the Bot using the emulator. However, the first user's credentials are cached in the emulator's Login Page and I am not asked to change to a different user.

## To Reproduce
1. Set up BotAuthenticationMSGraph sample and get it running
2. Log into the Bot using the Log prompt
3. Log out
4. Log in again - the credentials are not prompted. The prompt window appears with no content for a second then disappears. 
5. The bot claims I am logged in again using the old credentials.
6.  Restart bot sample as well as emulator.
7. Log in - same behavior as step 4.

## Expected behavior
1. Set up BotAuthenticationMSGraph sample and get it running
2. Log into the Bot using the Log prompt
3. Log out
4. Log in again - the prompt window appears and asks for username.  I choose a different user.
5. Bot works using new user.

## Screenshots
![image](https://user-images.githubusercontent.com/28765633/144109722-c9be28b5-b5d8-4c79-98f3-d8779a17e7b5.png)

[bug]

**Comment by dmvtech** [comment] 2021-12-02 16:54
Hi @mattsmall1972 I will attempt to reproduce and see if I get the same. 

Can you try a quick test by setting the `Use a sign-in verification code for OAuthCards` setting in Emulator? I'm assuming doing that will allow logout without issue, but I want to be sure.

**Comment by mattsmall1972** [comment] 2021-12-02 18:00
When I enable the sign-in verification code the same behavior occurs except with a code instead of silent authentication.  The emulator automatically logs me in using current credentials and does not give me the option to change credentials.

**Comment by dmvtech** [comment] 2021-12-07 22:50
Hi @mattsmall1972 I am able to reproduce similar. Do you see any errors in Emulator such as:

`[14:48:50]Failed to generate an actual sign-in link: Error: Failed to connect to ngrok instance for OAuth postback URL: FetchError: request to http://127.0.0.1:4041/api/tunnels failed, reason: connect ECONNREFUSED 127.0.0.1:4041`
OR
`[14:48:50]Falling back to emulated OAuth token.`

**Comment by mattsmall1972** [comment] 2021-12-08 16:04
I have not seen any error like that in the Emulator.

**Comment by dmvtech** [comment] 2021-12-16 23:44
Thanks @mattsmall1972 Do you see _any_ errors or anything in the Emulator logging/tracing pane? Does this reproduce in WebChat ([using ngrok](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-channel-ngrok?view=azure-bot-service-4.0) if needed)?

**Comment by dmvtech** [comment] 2021-12-28 21:40
Closing due to lack of reply and ability to reproduce exact error. If you still need assistance with this issue, please comment or reopen and we will continue.

**Closed by dmvtech** 2021-12-28 21:40 UTC
Labels: Bug, customer-reported, Bot Services, customer-replied-to
