### ISSUE TITLE
Bot Framework Emulator failed to run when an existing NODE_OPTIONS environment variable

### ISSUE THREAD

**Issue by xiaoyunwei** [microsoft/BotFramework-Emulator#2235] opened 2021-02-20 09:29 UTC
## Version
BotFramework-Emulator-4.11.0-windows and also some early versions.

## Describe the bug
Cannot run the emulator after installation. No error message is displayed.

## To Reproduce
1. Just double click the icon to start
2. Nothing happens

## Workaround
Delete the 'NODE_OPTIONS' environment variable and the emulator starts working.

## Screenshots
No error message is shown when running the exe directly. But you can find the error below when running from a console.
![image](https://user-images.githubusercontent.com/20653516/108590795-5f8d7600-73a0-11eb-8553-3337b609a6df.png)

**Comment by cwhitten** [comment] 2021-02-23 18:05
@tonyanziano can you take a look at this?

**Comment by tonyanziano** [comment] 2021-02-23 18:07
Sure, will do

**Comment by congysu** [comment] 2021-02-25 21:06
@tonyanziano could you please take a look at this item?  Thanks.

**Comment by tonyanziano** [comment] 2021-03-01 19:07
I can't seem to reproduce this. I have tried setting the `NODE_OPTIONS` variable and starting Emulator but it starts without any issues.

![image](https://user-images.githubusercontent.com/3452012/109545761-1c0cc900-7a7e-11eb-9201-a8e206871287.png)


If I set the `--max-http-header-size` option to have an empty value, electron will tell me that it needs an argument, so I know it is parsing the option out of the environment variable.

![image](https://user-images.githubusercontent.com/3452012/109545885-45c5f000-7a7e-11eb-8984-b431086315f6.png)


@xiaoyunwei what version of NodeJS are you running?

**Comment by xiaoyunwei** [comment] 2021-03-02 02:59
The version on my laptop is "v10.16.3". The one on my desktop is "14.16.0 LTS". Both had the same issue and it is OK now after removing the environment variable.

**Comment by tonyanziano** [comment] 2021-03-02 23:23
Thanks for the info.

I tried using version 4.11.0 of the Emulator (Electron 4.x) and was not able to reproduce this. I also tried it on the newer version of Emulator (Electron 11.x) and was unsuccessful as well.

@xiaoyunwei is there any chance you could show me what your `NODE_OPTIONS` environment variable looks like when you experience this issue?

You can run the following command:

`echo %NODE_OPTIONS%`

**Comment by xiaoyunwei** [comment] 2021-03-03 01:27
![image](https://user-images.githubusercontent.com/20653516/109738209-6028d680-7c02-11eb-8f23-8b68e2166056.png)

This is on a Windows 10 VM in Azure. I didn't install node.js separately on this VM.

**Comment by xiaoyunwei** [comment] 2021-03-03 01:29
> I can't seem to reproduce this. I have tried setting the `NODE_OPTIONS` variable and starting Emulator but it starts without any issues.
> 
> ![image](https://user-images.githubusercontent.com/3452012/109545761-1c0cc900-7a7e-11eb-9201-a8e206871287.png)
> 
> If I set the `--max-http-header-size` option to have an empty value, electron will tell me that it needs an argument, so I know it is parsing the option out of the environment variable.
> 
> ![image](https://user-images.githubusercontent.com/3452012/109545885-45c5f000-7a7e-11eb-8984-b431086315f6.png)
> 
> @xiaoyunwei what version of NodeJS are you running?

Can you just try deleting this variable? If it's not set, it uses the default value for max-http-header-size.

**Comment by tonyanziano** [comment] 2021-03-04 22:37
Interesting, I thought the missing double quotes would be the issue, but I was still unable to reproduce this:

![image](https://user-images.githubusercontent.com/3452012/110040126-1f5eb980-7cf7-11eb-8b41-d2d957dc4050.png)

I don't think we can just delete the variable inside of the code because it looks like electron is throwing the error before the app code is even loaded.

**Comment by tonyanziano** [comment] 2021-03-16 21:45
For now the workaround is to delete the `NODE_OPTIONS` environment variable if you encounter this issue.

I will try and repro this on a WIndows 10 VM in Azure

**Comment by tonyanziano** [comment] 2021-03-16 22:14
I tried reproducing this on a freshly created Windows 10 VM in Azure (Windows 10 Pro version 2004) and was unsuccessful:

![image](https://user-images.githubusercontent.com/3452012/111386824-0e546780-866a-11eb-989e-1b7655ef18db.png)

I'm going to close this issue for now as I am unable to reproduce this, and there appears to be a reliable workaround in which you delete the `NODE_OPTIONS` environment variable.

**Closed by tonyanziano** 2021-03-16 22:14 UTC
Labels: Bot Services, Bug, customer-replied-to, customer-reported
