### ISSUE TITLE
Centos 7: 'User added' sends tons of messages

### ISSUE THREAD

**Issue by daveta** [Microsoft/BotFramework-Emulator#1031] opened 2018-10-25 19:12 UTC
## Version
What version of the Emulator are you using. 4.0.0-preview-bugbash

## Describe the bug
`Conversation -> Send System Activity -> Conversation Update (User added event)` sends a ton of events

## Screenshots
<img width="767" alt="user-added" src="https://user-images.githubusercontent.com/6182197/47524236-e83a8c80-d84e-11e8-896a-9a36a5b178df.PNG">

## Additional context

[bug]

**Comment by justinwilaby** [comment] 2018-10-25 19:28
related to #991

**Comment by vishwacsena** [comment] 2018-10-25 20:56
Resolved as dupe of #991

**Closed by vishwacsena** 2018-10-25 20:56 UTC
Labels: 4.1, Approved, P1
