### ISSUE TITLE
OAuth prompt dialog disappears (Regression)

### ISSUE THREAD

**Issue by darrenj** [Microsoft/BotFramework-Emulator#1467] opened 2019-04-27 11:28 UTC
## Version
4.3.3.-56387

## Describe the bug
When clicking an oauthprompt a identity selection dialog is briefly shown not giving the user enough time to select. sometimes doesn't appear at all. It defaults to an identity (the wrong one) yielding oauthprompts not working

## To Reproduce
1.Click an oauthprompt and observe the window disappearing when shown briefly.

## Expected behavior
The user can select an identity and it not default

## Screenshots
Video capture doesn't show the identity selection box appearing due to behaviour of game mode on windows 10
![image](https://user-images.githubusercontent.com/33519520/56849044-6c95c700-68e7-11e9-8ac5-371a33e3978c.png)
[Bot Framework Emulator - vakonadj 2019-04-27 12-09-03.zip](https://github.com/Microsoft/BotFramework-Emulator/files/3123801/Bot.Framework.Emulator.-.vakonadj.2019-04-27.12-09-03.zip)

## Additional context

[bug]

**Comment by cwhitten** [comment] 2019-04-28 18:30
@darrenj We'll take a look at this soon. Do you know the most recent version of the Emulator where this was working as expected?

**Comment by darrenj** [comment] 2019-04-28 22:33
I'll try and check but last preview build was fine as far as I'm aware.

Sent from my 📱
________________________________

**Comment by justinwilaby** [comment] 2019-04-29 13:48
Related to #1354

**Comment by justinwilaby** [comment] 2019-04-29 13:53
This was not reproducible on a Mac when I took #1354. There is a known defect within Electron's chromium that selects the first cert in the store which is not guaranteed to be the correct one. This may be related and if so, it is not a trivial fix. 

@carlosscastro understood the problem and was looking into a possible fix a while back. I'll check with him to determine if a solution can be implemented.

**Comment by darrenj** [comment] 2019-04-29 13:57
Interesting, I only observed this issue coming back in the latest experimental build. Once I land I'll see if I can repro it working fine on the previous experimental build or perhaps something has changed on my machine that's caused the regression

**Comment by justinwilaby** [comment] 2019-04-29 20:22
@darrenj - 

Try logging into the Emulator using `File -> Sign in to Azure` and then sign out using `File -> Sign out`. This should clear any session data that may be shared between Auth prompts and effectively "reset" the Emulator. Afterwards, try the OAuth card again. If you still see the behavior, shutdown the Emulator, remove `Cookies` and `Cookies-journal` from the `C:\Users\<you>\AppData\Roaming\@bfemulator\main` directory and try once more. 

One of the paths above should solve the issue. If not, let me know and I'll continue to investigate...

**Comment by darrenj** [comment] 2019-04-30 19:52
Tested deleting the cookies/cookie/journal route and that resolved the issue. It stopped remembering any of the previous users and let me login using my selected account. As we explore options I wonder if the emulator might be best to have some form of "cookieless/icognitio-private" mode to help prevent the normally desirable caching/default selection of identity (SSO)

**Comment by tonyanziano** [comment] 2019-05-01 00:59
Closing this since there is an issue already tracking this, and a workaround exists.

**Closed by tonyanziano** 2019-05-01 00:59 UTC
