### ISSUE TITLE
ConversationUpdate not sent for "user"

### ISSUE THREAD

**Issue by michaelbrunner** [microsoft/BotFramework-Emulator#1568] opened 2019-05-13 06:35 UTC
## Version
4.4.1

## Describe the bug
Using the Bot Framework Emulator in Version 4.4.1 under Windows 10 the conversation can not be started. There should be two events to start a conversation. The Bot an the User must be registerd. The ConversationUpdate event for the bot is sent, but the event for the user is missing.
Switching back to version 4.2.1 of the Bot Framework Emulator solved the issue.
I also tried it on a Mac with version 4.4.1. Under MacOS I didn't have this issue!

## To Reproduce

1. Checkout Echo Bot from Bot Framework Examples
2. Set an breakpoint in the ActivityHelper OnTurnAsyn... method
3. Start the project 
4. Configure the Bot Framework Emulator in Version 4.4.1 on Windows 10 to connect to the local endpoint (e.g. http://localhost:3978/api/message)
5. The project will stop in the debugger, where you see that only conversationUpdate for the Bot is sent.

## Expected behavior
Both, bot and user, should be registered as conversation memebers.

[bug]

**Comment by tonyanziano** [comment] 2019-05-13 17:52
@michaelbrunner try updating to the [newest nightly build](https://github.com/microsoft/botframework-emulator-nightlies/releases/tag/v4.4.1-59264), or wait or the upcoming patch 4.4.2 and try again. I'm not able to reproduce this on Windows 10.

If i break inside of my echo bot, I see 2 distinct conversation update activities come in, one for adding the user, and one for the bot.

**Comment by michaelbrunner** [comment] 2019-05-17 10:09
@tonyanziano 
I tried with the latest nightly build, but got the same issue. Maybe it has something to do, because I am behind an enterprise proxy?
I will wait until next patch and use in the meanwhile an older version.

**Comment by tonyanziano** [comment] 2019-05-20 19:08
@michaelbrunner It is very possible that it has something to do with being behind a proxy; historically, corporate proxies have been the cause of a lot of friction for our users.

**Comment by martinoss** [comment] 2019-06-26 11:20
Same issue here (same company). Latest working version is 4.3.3. Starting with 4.4.0, the emulator is **never returning a response** to this request:

POST **http://localhost:29071/v3/directline/conversations** HTTP/1.1
Host: localhost:29071
Connection: keep-alive
Content-Length: 0
Authorization: Bearer eyJjb252ZXJzYXRpb25JZCI6IjljMzdmMGYwLTk3ZmUtMTFlOS04NDgyLWQzZDUyYjMwOGQwZXxsaXZlY2hhdCIsImNvbnZlcnNhdGlvbk1vZGUiOiJsaXZlY2hhdCIsImVuZHBvaW50SWQiOiJodHRwOi8vbG9jYWxob3N0OjM5NzgvYXBpL21lc3NhZ2VzIiwidXNlcklkIjoiNGQyZDBhZjItNjgxMC00ZWI4LWJjNmQtOTRlYmYxYTU3ZDMzIn0
Accept: application/json
Origin: file://
X-Requested-With: XMLHttpRequest
x-ms-bot-agent: DirectLine/3.0 (directlinejs; webchat)
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) BotFrameworkEmulator/**4.4.2** Chrome/69.0.3497.128 Electron/4.1.1 Safari/537.36
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US

With 4.3.3 the request looked like that:

POST http://localhost:29720/v3/conversations?botEndpoint=http://localhost:3978/api/messages&msaAppId=&msaPassword= HTTP/1.1
Host: localhost:29720
Connection: keep-alive
Content-Length: 151
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US
Content-Type: application/json
Origin: null
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) BotFrameworkEmulator/**4.3.3** Chrome/61.0.3163.100 Electron/2.0.12 Safari/537.36 botbuilder/emulator/4.3.3

{"bot":{"id":"8868f580-9801-11e9-ae1d-35b429b8cfa6","name":"Bot","role":"bot"},"members":[{"id":"4d2d0af2-6810-4eb8-bc6d-94ebf1a57d33","name":"User"}]}

Since all requests are locally as far that I know (no appId/pwd), I doubt that the corporate proxy is the issue. I can't see any other connection attempts in Fiddler.

Any idea what we can do to troubleshoot this error?

**Comment by JonathanFingold** [comment] 2020-08-06 23:56
I just hit this issue in Bot Framework Emulator version 4.9.0.

**Comment by tonyanziano** [comment] 2020-08-10 17:12
I'm unable to reproduce this issue on v4.9.0 @JonathanFingold .

If I set a breakpoint in the root of my bot, start a conversation with it from the Emulator, and select `conversationUpdate` from the menu in your screenshot, my breakpoint gets hit and the `turnContext.activity` points to the activity object for the conversation update:

![image](https://user-images.githubusercontent.com/3452012/89810416-e14b3f80-daf1-11ea-97ed-d77ae5f8343b.png)

Have you tried setting a breakpoint inside of your bot code and seeing if you get any incoming activity at all when selecting that menu item?

**Comment by JonathanFingold** [comment] 2020-08-11 19:53
This comes up after the conversation is already started, and I'm trying to add a "new" user to the conversation. Here are some screenshots:

When I try to add a new user, I see this in the Emulator:

![image](https://user-images.githubusercontent.com/35047199/89942433-66595600-dbd1-11ea-965c-ea438e8376fe.png)

But the breakpoint in my bot isn't hit:

![image](https://user-images.githubusercontent.com/35047199/89942333-3b6f0200-dbd1-11ea-87b6-fd0e1a0a38a0.png)

**Comment by tonyanziano** [comment] 2020-08-11 23:41
Can you send me your bot code or a simplified version of it that I can debug with? My alias is toanzian.

**Comment by JonathanFingold** [comment] 2020-08-12 21:34
Sent a copy via email.

**Comment by tonyanziano** [comment] 2020-08-12 22:48
Thanks @JonathanFingold . I can repro this with your code, and I think I know where the error is coming from.

**Note to fixer:** Mimic the behavior [as seen here in `chatSagas.ts`](https://github.com/microsoft/BotFramework-Emulator/blob/master/packages/app/client/src/state/sagas/chatSagas.ts#L657), and [hook up to `appMenuBuilder.ts` here.](https://github.com/microsoft/BotFramework-Emulator/blob/master/packages/app/main/src/appMenuBuilder.ts#L343)

**Comment by tonyanziano** [comment] 2020-09-09 22:57
I looked at the original issue which is / was supposedly caused by a special network configuration (company proxy / firewall), however, similar behavior was also mentioned in #2011 which was resolved and closed.

So I'm going to close this issue, please reopen this @martinoss if you are still encountering this behavior.

---

Regarding the separate bug opened by @JonathanFingold, also dealing with the conversation update, the fix for that bug will be tracked by #2175

**Closed by tonyanziano** 2020-09-09 22:57 UTC
Labels: Bot Services, Customer, customer-replied-to, customer-reported
