### ISSUE TITLE
Cannot emulate a specific user and/or conversation

### ISSUE THREAD

**Issue by Raseru** [Microsoft/BotFramework-Emulator#101] opened 2017-02-10 00:44 UTC
At the Microsoft emulator download page, it says you can "Emulate a specific user and/or conversation"

This newer emulator seems to have lost this feature.

**Comment by eanders-MS** [comment] 2017-02-10 00:48
Thank you for bringing this up. You are correct, the new emulator does not yet support these features. The ability to switch between users in a group conversation is coming soon. The ability to switch between conversations is also planned.

**Comment by navzam** [comment] 2018-06-28 17:42
Any update on this for the new emulator? In the previous version, I got around this by modifying `server.json` manually, but even that doesn't seem to work in the new version.

**Comment by tonyanziano** [comment] 2018-06-28 17:59
Hi @navzam ,

We do have a work item tracking this #522 , but it is currently in our backlog and has not yet been assigned to a milestone, although that may change.

**Comment by vishwacsena** [comment] 2018-08-07 20:07
dupe of #197

**Closed by vishwacsena** 2018-08-07 20:07 UTC
Labels: feature
