### ISSUE TITLE
Message not rendering even though it shows up in the Log section

### ISSUE THREAD

**Issue by lzc850612** [Microsoft/BotFramework-Emulator#1134] opened 2018-11-30 23:53 UTC
## Version
4.1.0

## Describe the bug
Messages not showing up even though they are showing up in the Log section of the emulator

## To Reproduce
This is hard to reproduce because i've only reproduced it in proactive messaging scenario. I have two emulator instances opened and i'm sending message to one instance and the other instance will receive the message. 

The activity: 

```json
{
  "type": "message",
  "id": "3e2cfd50-f4f9-11e8-acf9-bb1e8bae14c7",
  "timestamp": "2018-11-30T23:39:56.197Z",
  "serviceUrl": "http://localhost:62492",
  "channelId": "emulator",
  "from": {
    "id": "cbaf84f1-377b-4211-b740-e378d8e6e8c7",
    "name": "User",
    "role": "user"
  },
  "conversation": {
    "id": "6a126fa0-f4f8-11e8-b93f-437878a4770f|livechat"
  },
  "recipient": {
    "id": "cbaf84f1-377b-4211-b740-e378d8e6e8c7",
    "role": "user"
  },
  "text": "You have a meeting in 30 minutes in CCP with Lauren, do you want to navigate to the meeting location?",
  "speak": "You have a meeting in 30 minutes in CCP with Lauren, do you want to navigate to the meeting location?",
  "inputHint": "acceptingInput",
  "suggestedActions": {
    "actions": [
      {
        "type": "imBack",
        "title": "Yes",
        "value": "Yes"
      },
      {
        "type": "imBack",
        "title": "No",
        "value": "No"
      }
    ]
  },
  "attachments": [],
  "entities": [],
  "replyToId": "77246bd0-84fc-4aa7-9dbd-a2be1cab3f4d",
  "localTimestamp": "2018-11-30T15:39:56-08:00",
  "locale": ""
}
```

## Expected behavior
Proactive message should show up in the emulator

## Screenshots
![image](https://user-images.githubusercontent.com/4001684/49320660-bd7bcd80-f4b7-11e8-8324-2a5665e8217f.png)

## Additional context
transcript file: 

[message not rendering.zip](https://github.com/Microsoft/BotFramework-Emulator/files/2635338/message.not.rendering.zip)

Change the extension name .zip to .transcript to open it.

(Edited by @compulim for code formatting)

**Comment by compulim** [comment] 2018-12-03 19:29
In Web Chat v3, if `from` field say the activity is from the user, and the activity does not have `channelData`, then Web Chat will hide this message (because it think it is a post back.)

On the other hand, what we don't know is why proactive message sometimes work or not working. In the end of the day, for proactive messages, `from` should be bot.

**Comment by compulim** [comment] 2018-12-07 20:47
I am trying to repro with proactive sample from [BotBuilder-Samples](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/16.proactive-messages/bot.js).

The screenshot below is the message sent proactively from my bot.

![image](https://user-images.githubusercontent.com/1622400/49671736-a9871d00-fa1d-11e8-9d28-6253713dae38.png)

I didn't see anything wrong with the `from`. The field said the proactive message is sent from the bot and not the user.

If the `from` field is wrong and said `from.role === 'user'`, then the activity will not show up (due to weird logic in Web Chat). But the `activity.from.role` is correct, this activity will show up in Web Chat (and Emulator).

Will spend more time to investigate the issue.

@lzc850612 Can you tell us more on "2 instances of Emulator"? AFAIK, we don't support multi-user scenario today, and Emulator do not have UI to specific conversation ID to make it happen.

**Comment by compulim** [comment] 2018-12-07 20:57
We adopted the proactive message code in our MockBot, code is [here](https://github.com/compulim/BotFramework-MockBot/blob/master/src/commands/Proactive.ts).

**Comment by compulim** [comment] 2018-12-10 18:11
Cannot repro in the Emulator. My bot is trying to send a proactive message and Emulator do show up the activity.

![image](https://user-images.githubusercontent.com/1622400/49751985-cb71e100-fc63-11e8-9b13-4b99c0ca909d.png)

**Comment by compulim** [comment] 2018-12-10 18:14
@lzc850612 when you are composing the proactive message, did you set the `from` field?

This the code I used for testing. `reference` is the conversation reference JSON object I saved earlier.

```js
const adapter = new BotFrameworkAdapter({
  appId: process.env.MICROSOFT_APP_ID,
  appPassword: process.env.MICROSOFT_APP_PASSWORD
});

await adapter.continueConversation(reference, async continuedContext => {
  await continuedContext.sendActivity({
    text: 'This is a proactive message.',
    type: 'message'
  });
});
```

**Comment by compulim** [comment] 2018-12-10 20:04
Talked to @lzc850612 offline.

The problem is the proactive activity sent from the bot set `{ role: 'user' }`. Web Chat (v3) will hide anything that appears to be sent from the user but not actually sent from Web Chat.

Since this is a bot-specific issue, will close this for now.

**Closed by compulim** 2018-12-10 20:04 UTC
Labels: 4.3, Approved, P1
