### ISSUE TITLE
Doesn't stay logged in to Azure

### ISSUE THREAD

**Issue by q00u** [microsoft/BotFramework-Emulator#1986] opened 2019-11-13 01:32 UTC
## Version
What version of the Emulator are you using: 4

## Describe the bug
Give a clear and concise description of what the bug is:
I have to re-sign-in every time I open the bot framework emulator

## To Reproduce
1. Sign in with my Azure account.
2. Make sure the box to remember I'm signed in is checked.
3. Restart emulator.

## Expected behavior
Expected to still be signed in (because of the checkbox)

[bug]

**Comment by anusharavindrar** [comment] 2019-11-13 18:33
Hello @q00u , can you please specify as to which version of the Emulator are you using? The latest released version is 4.6.0 . I am on the latest version and tried to repro your issue, but I am able to stay logged in even after restarting the emulator.

**Comment by q00u** [comment] 2019-11-13 19:24
4.6.0 (4.6.0.21869 file version, 4.6.0.87405 product version)
Where is it supposed to be saving the log in information?

**Comment by q00u** [comment] 2019-11-13 19:39
Just uninstalled and re-installed the latest version (just in case).
No change. Problem remains.
This is on Windows 10, if that matters.

**Comment by anusharavindrar** [comment] 2019-11-13 19:44
That's strange since I am on the latest version on Windows 10 as well!! By any chance, are you trying to login to Azure on the Emulator by using a VPN?

**Comment by q00u** [comment] 2019-11-13 19:50
No VPN. It does log in successfully, it just forgets every time I restart. Frustrating, haha.

**Comment by anusharavindrar** [comment] 2019-11-13 19:55
Weird :confused: !! Can you try deleting the entire emulator folder and try installing again from the GitHub [release](https://github.com/Microsoft/BotFramework-Emulator/releases/tag/v4.6.0) page?

**Comment by q00u** [comment] 2019-11-13 20:14
1. Delete the emulator folder and reinstall from the GitHub release page

That's what I tried earlier.

2. Clear state

Just tried that too. No change. Still loses my sign in when I restart the emulator.

**Comment by tonyanziano** [comment] 2019-11-16 01:31
I'll take a look at the settings code and see if there is anything that would be causing the persistence to fail.

**Comment by anusharavindrar** [comment] 2019-11-19 23:19
@q00u so what basically happens in the background is that the user's Azure email should be saved in the server.json file located in the emulator application data folder. Can you try the following steps and get back to me with your findings?

-  Open the server.json file and make a copy of the JSON contents. The path to my server.json file in my system is as shown below:
![jsonemulator](https://user-images.githubusercontent.com/48731427/69194197-65314780-0add-11ea-88e5-9d361c6d35a2.png)

-  Go into the app settings on the emulator and change one of the options, and close the emulator.

-  Check the server.json again and make sure that the JSON changed accordingly.

Can you check and see if the option you changed is reflected in the JSON file correctly?

**Comment by q00u** [comment] 2019-11-21 18:43
The JSON is changing, but it's still not working.

The "users" entry is PACKED. Is this every time I signed in? An endless array of uuids and ids and "name": "User".

After I logged in (again) and exited, I confimred that "azure" had my login email address and "persistLogin": true, but even then, the next time I opened the emulator, I wasn't logged in. _Even though the info was still in the server.json!_

I deleted server.json and started fresh. The wall of "users" went away, but nothing changed. Despite being logged in, and having my login email saved in the JSON, I still wasn't logged in when I restarted the emulator.

"azure" is filled. "users" has one user, and "currentUserId" points to it. And I'm still not logged in.

**Comment by anusharavindrar** [comment] 2019-11-25 18:36
@q00u the "users" entry is always filled with an array of uuids, ids and name every time you sign in. Also, when you sign out of Azure and close the emulator, the updated server.json should have the Azure field as
 "azure": {
    "signedInUser": "",
    "persistLogin": true
  }
When you sign out of Azure and close the emulator, does the server.json get updated to the same as above ?
@tonyanziano would you like to suggest any other work around to help narrow down the issue?

**Comment by tonyanziano** [comment] 2019-11-25 18:47
Hi @q00u ,

Currently, the `users` entry does get filled up with GUIDs that aren't really necessary, and we have plans to fix that soon.

I'm not sure why the login is not persisting for you in this case when your info is clearly being saved to the `server.json` file.

I'll have to take a closer look at this issue, however, in this current release schedule we have prioritized fixing Mac OS accessibility issues that need to be resolved before we go to production. The accessibility work will have to take precedence before I get around to the login issue, but I will try to address it soon.

**Comment by q00u** [comment] 2019-11-25 19:13
@anusharavindrar Yup, signed out and closed emulator, and indeed that's what the "azure" section looks like. (Also tried logging back in after manually logging out, but it still doesn't persist)

@tonyanziano No worries. It's not like it doesn't function when I'm not logged in.

**Comment by tonyanziano** [comment] 2020-02-10 23:41
This has been bumped out of the current release's planning. I will revisit this issue following the current release.

**Comment by cwhitten** [comment] 2020-03-17 20:35
@q00u we've recently release a new update to the Emulator, can you update your version and try again?

**Comment by q00u** [comment] 2020-04-21 17:38
Sorry for slow reply, I'm only just now getting back to MS Bot Framework projects at work.

So, new work computer, fresh download of 4.8.1, and...

It still doesn't remember me when I re-open the Bot Framework Emulator. :-(

**Comment by cwhitten** [comment] 2020-08-04 21:14
Closing as being unable to reproduce.

**Closed by cwhitten** 2020-08-04 21:14 UTC
Labels: Bot Services, Bug, R10, customer-replied-to, customer-reported
