### ISSUE TITLE
[MAS4.2.10] [Screen reader-Open Bot] In browse mode NVDA focus is not moving to the “Bot URL” text field 

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1824] opened 2019-09-04 12:54 UTC
**Actual Result:**
In browse mode NVDA focus is not moving to the “Bot URL” text field present in the Open bot dialog 

**Expected Result:**
In browse mode NVDA focus should moves  to the “Bot URL” text field and should read the bot url text field information 

**Repro Steps:**
Turn on the NVDA 
1. Open the Bot Framework V4 Emulator.
2. Welcome tab screen gets opened
3. Navigate to the Open bot and select it 
4.Dialog gets opened  
5.Navigate to the Bot URL text field using browse mode (Down arrow key) 
5. Observe the issue 

**User Impact:**
Users who rely on screen reader will be affected if the screen reader focus is not moving to the text field element then the screen reader users will miss the feature 

**Test Environment:**
OS Build: Version 1903(OS Build 18362.295)
Application: Bot Framework V4 Emulator
Screen reader: NVDA 

**MAS Reference :**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={b24201d1-2276-4471-8183-e1e5353031ad}
[MAS4.2.10_Open Bot.zip](https://github.com/microsoft/BotFramework-Emulator/files/3574572/MAS4.2.10_Open.Bot.zip)

**Comment by corinagum** [comment] 2019-09-10 22:55
I am no longer able to reproduce this issue. Can we verify? Thanks!

**Comment by Kumar2608** [comment] 2019-09-12 07:30
Verified in latest bot emulator Version 4.5.2-78641 with NVDA(2019.2 ) and issue still repro'ing.
Hence reactivating the bug. Please refer the attachment:1824.zip
[1824.zip](https://github.com/microsoft/BotFramework-Emulator/files/3604239/1824.zip)

**Comment by corinagum** [comment] 2019-09-18 18:22
@corinagum verify and assign to Southworks

**Comment by awalia13** [comment] 2019-10-08 23:47
This seems a bug with NVDA/JAWS as it's working fine with Narrator.
@Kumar2608  - Can you please file a bug with NVDA Team.

**Comment by corinagum** [comment] 2019-10-09 18:26
I'm removing this from 4.6 and un-assigning myself. I will not be closing, since this is still an Accessibility issue, but is not within our ability to fix before the 4.6 deadline.

**Comment by tonyanziano** [comment] 2019-10-11 07:45
a11y team said this would be closed once a bug is logged on NVDA.

**Comment by ShikhaMishra11** [comment] 2019-10-25 06:03
Its NVDA specific bug ,logged the bug in NVDA path so closing the bug

**Closed by ShikhaMishra11** 2019-10-25 06:03 UTC
Labels: A11yCT, A11yMAS, A11yMediumImpact, Accessibility, Bug, Emulator-Win, ExternalA11y, HCL-BotFrameworkEmulator, MAS4.2.10, Severity3
