### ISSUE TITLE
Focus lost on text input fields in emulator Settings

### ISSUE THREAD

**Issue by dvanbler-accuserve** [microsoft/BotFramework-Emulator#2416] opened 2023-02-10 14:44 UTC
Using Bot Framework Emulator 4.14.1 on Windows 10: when attempting to use the emulator Settings screen, the input focus constantly switches to the "Path to ngrok" text field.

1. Focus on the "localhost override" field. Wait for ngrok status to update (10-20 seconds). Focus will automatically switch back to the "Path to ngrok" field.
2. Attempt to type into the "localhost override" field. Focus will immediately change to the "Path to ngrok" field.

This obviously makes editing settings on this page difficult. You have to copy/paste text into the text fields to avoid the focus switching.

**Comment by johnataylor** [comment] 2023-02-28 18:52
I'm not able to reproduce this issue on 4.14.1 running on Windows 11.
Could you clarify the repro steps, it's possible I'm not following exactly the same set up.

Closing this issue. If you continue to see this issue please reopen.

**Closed by johnataylor** 2023-02-28 18:52 UTC
Labels: Bug, customer-reported, Bot Services

**Comment by dvanbler-accuserve** [comment] 2023-02-28 19:18
Steps to reproduce:

1. Open Bot Framework Emulator (in my case v4.14.1 on windows 10)
2. Click on the Settings gear icon in lower left corner
3. Attempt to enter text into any of the text boxes (except for "Path to ngrok")
4. After I type the first character, the focus switches to the "Path to ngrok" textbox.

I have attached a short video that demonstrates the issue.

https://user-images.githubusercontent.com/104215820/221956263-f151997f-9513-4da3-998c-f5bc58856068.mp4
