### ISSUE TITLE
Clicking "Sign In" on an OAuth Card opens the file explorer  

### ISSUE THREAD

**Issue by JeganBas** [microsoft/BotFramework-Emulator#2130] opened 2020-04-16 10:21 UTC
In the recent version 4.8.1 of Emulator, 
I'm running the Authentication sample Bot, in that while Signing in , the emulator is not redirecting to a browser window to generate the token, instead it is opening the explorer window. 

Is there any fix or workaround for this issue. 

because of this issue I'm unable to debug my project, also this issue is not there in the previous version,

**Comment by axelsrz** [comment] 2020-04-16 18:09
Hey @dmvtech could you take a look at this one? Thanks

**Comment by dmvtech** [comment] 2020-04-16 18:14
@JeganBas If not already done, can you confirm this reproduces after selecting `Clear state` from the `File` menu?

If so, can you please grab a fiddler trace. You can send to me at v-danava@microsoft.com

**Comment by JeganBas** [comment] 2020-04-20 06:23
Even after clearing the state it's the same results,  the emulator keep opening the explorer window instead of browser while signing in.  I'm unable to use fiddler here. Suggest me a different solution please

**Comment by dmvtech** [comment] 2020-04-22 02:49
I am able to reproduce. To clarify; it is opening File Explorer (explorer.exe).

**Comment by dmvtech** [comment] 2020-04-22 02:55
Looks like a regression #1397 

@tonyanziano

**Comment by JeganBas** [comment] 2020-04-22 08:42
@dmvtech  yes  , its opening the File explorer only, what could be the fix for this ?

**Comment by tonyanziano** [comment] 2020-04-22 16:19
Thanks for looking into this @dmvtech .

I'll dig around a bit once I get an auth sample working. It's possible that something changed inside Web Chat and that's the cause, but that's just a hunch at the moment.

**Comment by tonyanziano** [comment] 2020-04-22 21:43
I tried to reproduce it, but I can't on my end 🤔

![image](https://user-images.githubusercontent.com/3452012/80036805-4e858700-84a7-11ea-94b7-8d48526be5c9.png)

This is on v4.8.1. 

@JeganBas if you downgrade to a previous version, like 4.8.0 or 4.7, do you still experience this issue? If we could narrow it down to a certain version then we can look at the delta in the past commits and see if there is anything that might have caused it.

**Comment by JeganBas** [comment] 2020-04-27 04:41
Hi @tonyanziano , I've downgarded to Emulator 4.7 and now i can able to sign In, so the problem is only in 4.8.1

**Comment by tonyanziano** [comment] 2020-04-27 16:32
Thanks for testing that out @JeganBas ,

We can take a look at what changed between 4.7 and 4.8.1 and see if there are any obvious commits that might have caused this behavior.

**Comment by geo-msft** [comment] 2020-05-07 09:11
hi, if you set the path to ngrok in the emulator settings, the Oauth Card will show the expected result: the prompt to login: 

![image](https://user-images.githubusercontent.com/57954688/81276538-d351d280-905b-11ea-8a51-a1b95e593334.png)

After multiple tests, I noticed the issue happens when the path is empty.

**Comment by tonyanziano** [comment] 2020-06-05 19:35
I'm now able to reproduce this reliably.

[Video for reference](https://recordit.co/qJH4zTGVpA)

This is indeed a bug in the sense that clicking the sign-in link should not open the file explorer, however, that being said, the following still remains true:

- When reproducing this bug, as you can see in the video I posted, as soon as the sign-in card is generated, an error message is printed out in the Emulator log panel stating that the Emulator was unable to start up ngrok due to the ngrok path being wrong or blank in the app setting page. This is the correct behavior, and receiving an actual OAuth token without configuring ngrok is still impossible and will remain this way.

- When ngrok is not configured, clicking on the sign-in card should still cause the Emulator to give the bot a token, however it will be an emulated token (not generated by the token service) prefixed with `emulatedToken_` that the user can use for testing purposes

- Once I fix this bug, the user will once again be able to get an emulated token from the Emulator when ngrok is not configured

**Comment by tonyanziano** [comment] 2020-06-09 17:24
This fix will be in the next nightly build (usually gets published around 11 PM PST).

**Closed** 2020-06-09 17:23 UTC
Labels: Bot Services, Bug, R10, customer-replied-to, customer-reported

**Comment by JeganBas** [comment] 2020-06-16 04:02
@tonyanziano thanks for updating, i will  validate the new build and update you
