### ISSUE TITLE
If you open the same transcript twice the tab title changes to 'transcript'

### ISSUE THREAD

**Issue by tomlm** [Microsoft/BotFramework-Emulator#1264] opened 2019-01-28 19:24 UTC
## Version
4.2.16766

## Describe the bug
When you open the same transcript file twice the existing tab gets changed to 'transcript'

## To Reproduce
1. Open transcript 'ConfirmPrompt.transcript'
Tab looks like this:

![image](https://user-images.githubusercontent.com/17789481/51860719-444dfa80-22ef-11e9-9f3f-535d7e62d7c8.png)

2. Open transcript 'ConfirmPrompt.transcript' again 
Now it looks like this:
![image](https://user-images.githubusercontent.com/17789481/51860675-31d3c100-22ef-11e9-9e9e-8e160876e6fd.png)

## Expected behavior
To not rename the tab and to switch to that tab.

[bug]

**Comment by tonyanziano** [comment] 2019-01-28 20:08
This is a dupe of #1216

**Closed by tonyanziano** 2019-01-28 20:08 UTC
