### ISSUE TITLE
Emulator: LUIS inspector, TRAIN spinner doesn't stop and PUBLISH stays disabled

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#920] opened 2018-09-21 00:25 UTC
**version botframework-emulator-setup-4.0.577-nightly**
Related bug: #810?

When you reassign a user message to a different intent, it is unclear when the model has been updated because:

1. The log message "[LUIS] Intent reassigned successfully" appears right after you select an intent from the "Reassign Intent" dropdown but before you hit the Train button
2. When you hit the Train button, it never stops spinning, even if the model has successfully trained

**Repro steps**
1. Open a bot that uses LUIS and start talking to it.
2. From the log panel, choose a Luis trace message. This opens the LUIS inspector:
![screenshot 208](https://user-images.githubusercontent.com/39317542/45853271-221cee00-bcf9-11e8-87fc-2ae678bd5abc.png)

3. In the LUIS inspector, choose a different intent from the "Reassign Intent" dropdown. This causes the log message "[LUIS] Intent reassigned successfully" to appear (even though the model has not been trained):
![screenshot 209](https://user-images.githubusercontent.com/39317542/45853305-57c1d700-bcf9-11e8-9bd2-2546b16b948d.png)

![screenshot 210](https://user-images.githubusercontent.com/39317542/45853327-788a2c80-bcf9-11e8-97bf-39e72961038d.png)

4. Press the Train button. The progress spinner appears:
![screenshot 211](https://user-images.githubusercontent.com/39317542/45853355-a1122680-bcf9-11e8-9bc1-ae56f868ffe3.png)

5. The progress spinner doesn't go away, even after the model has been trained (in the screenshot below you can see in LUIS.ai that the intent has been successful reassigned and the spinner has been spinning for several minutes):
![screenshot 212](https://user-images.githubusercontent.com/39317542/45853407-e8001c00-bcf9-11e8-9505-9aa7577f6824.png)

**Comment by justinwilaby** [comment] 2018-09-21 03:05
The reassignment of the intent when the dropdown is changed is by design. If the spinner stays after successfully training, there could be a problem with how the response is processed or possibly with the API itself. This warrants investigation.

**Comment by mewa1024** [comment] 2018-09-21 16:40
Ah, I see--so "[LUIS] Intent reassigned successfully" is technically correct in that the API call has been made. While technically correct, the message implies that the user doesn't need to do anything else, when in fact they need to train their model for the reassignment to make a difference to the model. I'll file revisiting the LUIS messages as a separate, future, issue and edit name of this bug.

**Comment by sgellock** [comment] 2018-09-21 18:05
pushing out post ignite

**Comment by justinwilaby** [comment] 2018-09-26 15:58
This can be reprod when the api call to the luis service fails. The `catch` block fails to set the state of the button back to default which causes the spinner to remain.

**Comment by justinwilaby** [comment] 2018-09-26 16:02
Fixed by #929

**Closed** 2018-09-26 16:44 UTC
Labels: P1, bug, v4
