### ISSUE TITLE
[Chatdown] Suggestions are not displayed

### ISSUE THREAD

**Issue by cytops** [Microsoft/BotFramework-Emulator#1372] opened 2019-03-13 15:47 UTC
## Version
4.3.0.50450

## Describe the bug
[Suggestions=] command from chatdown is not displayed.

## To Reproduce
1. Create a test.chat file
2. Write:
```
bot: some suggestions
bot: [Suggestions=yes|no]
```
3. convert it to transcript: `chatdown test.chat > test.transcript`
4. open test.transcript in Bot Framework Emulator

## Expected behavior
Bot Framework Emulator should display the suggestions "yes" and "no" after the text "some suggestions".

## Additional context
The message is logged and the inspector displays the JSON which seems to be well formatted:
```
...
{
  "channelId": "chatdown",
  "conversation": {
    "id": "4b008870-45a4-11e9-8f60-15ac963992b1|transcript"
  },
  "from": {
    "id": "bot",
    "name": "bot",
    "role": "bot"
  },
  "id": "2",
  "recipient": {
    "id": "494e802e-2570-4d16-90b3-7051f6e190b1",
    "name": "user",
    "role": "user"
  },
  "showInInspector": true,
  "suggestedActions": {
    "actions": [
      {
        "title": "yes",
        "type": "imBack",
        "value": "yes"
      },
      {
        "title": "no",
        "type": "imBack",
        "value": "no"
      }
    ]
  },
  "text": "",
  "timestamp": "2019-03-13T15:25:03.100Z",
  "type": "message"
}
```

**Comment by justinwilaby** [comment] 2019-03-13 21:16
I am able to repro this and it looks like a WebChat regression. 

@corinagum, @compulim - I can see the json is formatted correctly and webchat does show the message in a faint line but no suggested actions are rendered.

![image](https://user-images.githubusercontent.com/2652885/54315112-8f1f8b00-459a-11e9-937a-3dd3c792d1a1.png)

**Comment by justinwilaby** [comment] 2019-03-13 21:56
@cytops - talking with @corinagum we've confirmed that suggested actions do not show up in WebChat when in "transcript" mode. When using a live sample bot, suggested actions display as expected:
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/2652885/54317370-29360200-45a0-11e9-9f1b-a31ca7facdf2.png">

I'm closing this as WAD.

**Closed by justinwilaby** 2019-03-13 21:56 UTC
Labels: Bug

**Comment by cytops** [comment] 2019-03-13 22:06
Thanks @justinwilaby for your answer.

But...is it an expected behavior on transcript mode? If the answer is positive, should I create another issue as a "feature request" to request this (very) useful feature?

**Comment by a-b-r-o-w-n** [comment] 2019-03-13 22:31
@cytops Thanks for the suggestion. The current behavior is actually a limitation with the webchat component. We are discussing as a team how to proceed. We may end up tracking that work in the [webchat project](https://github.com/Microsoft/BotFramework-WebChat).
