### ISSUE TITLE
My Bot is running Locally with APp id and password but when host in azure

### ISSUE THREAD

**Issue by hardikchoudhary** [Microsoft/BotFramework-Emulator#233] opened 2017-06-19 18:34 UTC
Getting always retry in dev framework test web chat

and issues are there https status code

There was an error sending this message to your bot: HTTP status code NotFound

Please help me regarding the same

**Comment by nwhitmont** [comment] 2017-06-20 16:10
Duplicate of https://github.com/Microsoft/BotBuilder/issues/2985

**Closed** 2017-06-21 02:12 UTC
