### ISSUE TITLE
Message Attachment (card) w/in Carousel cannot be tapped to open url

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/BotFramework-Emulator#121] opened 2017-03-15 20:36 UTC
**OS**: Windows
**OS Version**: 10.15042.3
**Emulator Version**: 3.5.25
**SDK**: C# v3.5.5

The following response from a bot:
```
"attachmentLayout": "carousel",
  "locale": "en-US",
  "text": "",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.thumbnail",
      "content": {
        "title": "GeekTrainer",
        "images": [
          {
            "url": "https://avatars2.githubusercontent.com/u/6109729?v=3"
          }
        ],
        "tap": {
          "type": "openUrl",
          "title": "Click to open in your browser",
          "value": "https://github.com/GeekTrainer"
        }
      }
    },
    {
      "contentType": "application/vnd.microsoft.card.thumbnail",
      "content": {
        "title": "Xophmeister",
        "images": [
          {
            "url": "https://avatars3.githubusercontent.com/u/384987?v=3"
          }
        ],
        "tap": {
          "type": "openUrl",
          "title": "Click to open in your browser",
          "value": "https://github.com/Xophmeister"
        }
      }
    }
```
results in a carousel with items that, although specifying `tap` actions on the thumbnail card of type `openUrl` with a corresponding URL, cannot be clicked on to fire a browser to open the associated URL.

Other things I've tried (without success):
* HeroCard vs Thumbnail
* Layout as List vs Carousel
* `openUrl` as the Tap action for the image in the card

**Comment by danmarshall** [comment] 2017-03-16 00:39
Hi @brandonh-msft - thanks for filing issues :) if you think the issue is isolated to the WebChat pane, you may want to file the issues in the WebChat repo: https://github.com/Microsoft/BotFramework-webchat

**Comment by eanders-MS** [comment] 2017-03-16 05:17
Hi @brandonh-msft Thanks for taking the time to report this. This issue has been fixed in the WebChat control and will be available in the next emulator release. (Related: https://github.com/Microsoft/BotFramework-WebChat/issues/339)

**Closed by eanders-MS** 2017-03-16 05:17 UTC

**Comment by brandonh-msft** [comment] 2017-03-16 15:40
@danmarshall will do in the future; only after filing these was I even made aware the emulator shared the webchat :) good to know!
