### ISSUE TITLE
OAuthPrompt for ADAL is retriggering

### ISSUE THREAD

**Issue by d0ggyRul3z** [Microsoft/BotFramework-Emulator#995] opened 2018-10-17 00:18 UTC
## Version
v4.0.41504

## Describe the bug
When you click on the OAuthPrompt, it will retrigger the prompt and does not open up the Azure ADAL auth sign-in window.

## To Reproduce
1. Get https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/18.bot-authentication
2. Follow guide here - https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp
3. Debug it in Visual Studio
4. See error on emulator

## Expected behavior
Azure ADAL auth sign-in window to show

related to https://github.com/Microsoft/BotFramework-Emulator/issues/768 ?

[bug]

**Comment by punitganshani** [comment] 2018-10-21 14:33
Facing same issue. Added details [here](https://stackoverflow.com/questions/52914704/oauthprompt-is-never-invoked-in-botframework-v4)

**Comment by justinwilaby** [comment] 2018-10-22 14:33
This is likely fixed with #1008. Please try this again with [this build](https://github.com/Microsoft/BotFramework-Emulator/releases/tag/untagged-419fb9ba0d297567e176) and let me know if the problem is fixed.

**Comment by sgellock** [comment] 2018-10-22 18:14
moving to 4.2 as we believe this is fixed in 4.1, but want to give the community time to verify with the above state build.

**Comment by d0ggyRul3z** [comment] 2018-10-23 01:30
@justinwilaby , I'll give it a go and let you know

**Comment by justinwilaby** [comment] 2018-10-24 15:34
@d0ggyRul3z - I updated the comment and link to point to the releases section. You can grab the latest build there. 👍

**Comment by justinwilaby** [comment] 2018-10-30 21:39
fixed with #1008

**Closed by justinwilaby** 2018-10-30 21:39 UTC
Labels: 4.2, Bug
