### ISSUE TITLE
Can't open Bot file

### ISSUE THREAD

**Issue by enKoding** [microsoft/BotFramework-Emulator#1519] opened 2019-05-04 14:41 UTC
## Version
4.4.0 (macOS 10.14.4)

## Describe the bug
Not able to open my Bot File. 

## To Reproduce
1. Go to "Open Bot"
2. Select my .bot File
3. Click to "Connect"
4. Type Bot file's secret
5. Click "Submit"

## Expected behavior
Being able to debug my Bot

**An Error occurred opening the Bot at [Path] Error: [confirmAndOpenBotFromFile] Error while calling browserForBotFile: No secret provided to decrypt encrypted bot.**

**Comment by cwhitten** [comment] 2019-05-04 15:48
Hi @enKoding. I'm seeing similar behavior around the Emulator's mechanisms to encrypt .bot files using this secret. We will take a look at this first thing. Thanks for your patience as we address this. 

Unencrypted .bot files don't appear to be affected.

**Comment by cwhitten** [comment] 2019-05-04 18:39
The issue is due to the need to bump the Emulator's dependency on `botframework-config` to version `4.4.0`. This change is in flight.

**Comment by enKoding** [comment] 2019-05-04 20:40
Is this a change I can apply my self for now ? If so, How ?

**Comment by cwhitten** [comment] 2019-05-04 21:02
@enKoding it may be 24 - 48hrs until this change is available in a packaged version. If you're familiar enough with git workflows and wanted to build the Emulator from source by cloning, installing, and running the Emulator in a development mode, the change is on this branch:

https://github.com/Microsoft/BotFramework-Emulator/pull/1521

**Comment by cwhitten** [comment] 2019-05-06 21:31
addressed in https://github.com/microsoft/BotFramework-Emulator/pull/1521

**Closed by cwhitten** 2019-05-06 21:31 UTC
Labels: Bug
