### ISSUE TITLE
Installer does not install to computer

### ISSUE THREAD

**Issue by Spydernaz** [Microsoft/BotFramework-Emulator#181] opened 2017-05-08 00:56 UTC
Installer on windows does not install the application. I have to run the installer every time

**Comment by eanders-MS** [comment] 2017-05-08 01:09
Apologies, it's a bug in the latest version. We'll have a fix out next week.

**Comment by Spydernaz** [comment] 2017-05-08 04:43
Thanks :)

**Comment by diegoenriquesantos** [comment] 2017-05-08 12:32
Spydernaz, in 3.5.27 versión, I have installed in the following path: C:\Users\diego\AppData\Local\botframework\app-3.5.27\botframework-emulator.exe

The problem is that in this version not create the shortcut to botframework-emulator.exe.

Regards.

**Comment by eanders-MS** [comment] 2017-05-09 17:23
Updated version is now available, with a fix for this issue. Direct download link: https://github.com/Microsoft/BotFramework-Emulator/releases

**Closed** 2017-05-10 17:42 UTC

**Comment by Spydernaz** [comment] 2017-05-11 07:02
thanks
