### ISSUE TITLE
Bot emulator responds slowly or doesnt respond, nothing appears in Log window even if bot replies

### ISSUE THREAD

**Issue by jayforu** [Microsoft/BotFramework-Emulator#370] opened 2017-12-18 13:51 UTC
I am new to node js
Trying sample code from Microsoft, attaching everything in word file
Most of the times emulator is not able to send message, running over home wifi connection
I tried to enable debug mode, but nothing appears in Log window of emulator

![image](https://user-images.githubusercontent.com/12219098/34109067-74310eb0-e428-11e7-8537-50228df27d0f.png)
![image](https://user-images.githubusercontent.com/12219098/34109123-9f33e83a-e428-11e7-995e-e0c94c84b4a7.png)
[Bot emulator problem.docx](https://github.com/Microsoft/BotFramework-Emulator/files/1568105/Bot.emulator.problem.docx)

**Comment by jayforu** [comment] 2017-12-18 13:59
Am I making any mistake in setting up debug mode? What could be the reason behind not seeing anything in Log panel?

**Comment by eanders-MS** [comment] 2017-12-18 17:43
The log window appears below the Log header in the bottom right of the app. There's a bug in the current emulator release where the Log panel is sized to zero height. You can grab its sizer bar and pull it up.

**Comment by jayforu** [comment] 2017-12-18 18:15
Thanks a ton!

Thanks and Regards,

Jayraj Vahadane,
M.D., Creative Producer,
Pole Star Entertainment Pvt. Ltd.
Cell#09890319025, Office#020-27702074

**Comment by eanders-MS** [comment] 2017-12-19 16:29
Sounds like the issue is resolved. Closing now. Post here if you'd like it reopened.

**Closed by eanders-MS** 2017-12-19 16:29 UTC
