### ISSUE TITLE
Adding a "Qna Maker" service doesn't provide all KB from all your subscriptions

### ISSUE THREAD

**Issue by MrLuje** [microsoft/BotFramework-Emulator#1462] opened 2019-04-25 09:52 UTC
## Version
4.3.3

## Describe the bug
Adding a new "Qna Maker" from the service menu doesn't give all knowledge bases from all my subscriptions.

## To Reproduce
1. Open an existing bot file
2. Click on 'Add a new service"
3. Select "Add Qna Maker"
4. Some KB are missing

## Expected behavior
All KBs linked to my account should be visible

## Screenshots

![image](https://user-images.githubusercontent.com/632075/56727125-53a6dd80-6750-11e9-81f9-b9262ae9c0aa.png)

![image](https://user-images.githubusercontent.com/632075/56726806-c5325c00-674f-11e9-91d0-bff281f3e3f7.png)

## Additional context
I tried adding another KB on the other subscription and it also doesn't show up (was wondering if the same name could cause the issue)

**Comment by justinwilaby** [comment] 2019-04-25 13:40
@MrLuje - Thank you for the submission.

This is a known issue and has to do with [multi-tenant](https://docs.microsoft.com/en-us/azure/active-directory/develop/single-and-multi-tenant-apps) applications which Q&A Maker is configured to be. The access token retrieved from logging into Azure AD defaults to the first tenant which means only KBs from that tenant are retrieved. The Q&A APIs haven't been revisited in some time so it is possible there is an API available that takes this into account. 

I'll investigate this and determine if a change can be made to fix this. Also, some upcoming changes to the Emulator might mean services are managed differently. If these changes are decided on, we will hold off on a fix.

**Comment by cwhitten** [comment] 2021-02-26 00:38
Closing as a duplicate of https://github.com/microsoft/BotFramework-Emulator/issues/1821

**Closed by cwhitten** 2021-02-26 00:38 UTC
Labels: Customer
