### ISSUE TITLE
Cannot connect to LUIS during trace inspection

### ISSUE THREAD

**Issue by kolexinfos** [Microsoft/BotFramework-Emulator#663] opened 2018-06-29 10:21 UTC
Hello Team,
After connecting to my LUIS app, it gives Unauthorized as shown in the attached message below
![luiserror](https://user-images.githubusercontent.com/1893821/42087570-7ce90870-7b8e-11e8-91da-d218c8981900.png)

I do not understand where the error is coming and I am unable to Train and Publish to my LUIS app from the Emulator.

**Comment by Zerryth** [comment] 2018-06-29 22:50
Attempting to reproduce the issue with another engineer, we both were unable to connect LUIS via the emulator at all, and in turn don't have the ability to Train/Publish LUIS app from emulator

Putting in credentials to connect to LUIS service:
![connectingtoluisapplication](https://user-images.githubusercontent.com/35248895/42117765-774ae4fe-7bb3-11e8-8e64-6dcf0c8721a0.PNG)

After clicking "Submit", LUIS still not connected in emulator
![luisnotconnectedstill](https://user-images.githubusercontent.com/35248895/42117792-b0acb59c-7bb3-11e8-887e-a8a773b9b35c.PNG)

**Comment by tonyanziano** [comment] 2018-07-20 17:42
@Zerryth it looks like you're running into bug #642 where adding the service via the UI is not persisting in the UI or being written to the bot file.

This is due to be fixed in our next milestone.

**Comment by vishwacsena** [comment] 2018-09-01 18:15
Not fixed in 
![image](https://user-images.githubusercontent.com/20918136/44948763-4495a880-add8-11e8-854b-71a4d35c6091.png)

**Comment by justinwilaby** [comment] 2018-09-13 00:11
This should be fixed in the current nightly:
![image](https://user-images.githubusercontent.com/2652885/45459775-c88c4200-b6ae-11e8-9296-74cfe8daa0b3.png)

**Closed by justinwilaby** 2018-09-13 00:11 UTC
Labels: Approved, Next-Iteration, P0, bug, v4

**Comment by brazierdavid** [comment] 2018-11-16 11:35
What was the fix?  I have the same problem, running from repo source code.  I suspect it may be because it is using the authoring key as a subscription key, and since our starter key (= authoring key) ran out of quota and we added a proper subscription key to the LUIS apps, we get "Unauthorized".  It should use the subscription key from the .bot config.
