### ISSUE TITLE
[MAS4.2.1][Screen Reader-Connect the bot] Voiceover reads the all content present in the conversation pane in a same flow.

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1895] opened 2019-10-03 07:17 UTC
**Actual Result:**
When focus lands on the conversation pane after link, the voiceover reads the all content in a same flow as they are defined in the complementary landmark.

**Expected Result:**
The voiceover should only informs about the complementary landmark when the focus lands on the whole pane.

**Note:**
Same issue found in Debug, here the voiceover narrates the whole content of the conversation pane in a same flow.

**Repro Steps:**
1. Open the Bot Framework V4 Emulator.
2. Welcome tab screen gets opened.
3. Navigate to the "Open Bot" button and activate it.
4. Open a Bot Dialog box gets opened.
5. Navigate to the "bot URL" edit box and enter URL- http://localhost:3978/api/messages
6. Navigate to "Connect" button and activate it.
7. "Live Chat" separate window appears.
8. Navigate to "Type a message" edit box and send some messages.
9. Now, navigate the pane in voiceover mode and observe the issue after "http://localhost:3978/api/messages".

**User Impact:**
Voiceover dependent users will find difficulty to understand and navigate the page if the landmark are announced in a same flow.

**Test Environment:**
OS: MacOs Version 10.15
Application: Bot Framework V4 Emulator (Version 4.5.2-80829)

**Impacted MAS Link:**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={a12f3779-bdf1-40c2-bbcc-0e314ea94858}](url)

**Attachment:**
[Voice reads whole content.zip](https://github.com/microsoft/BotFramework-Emulator/files/3684873/Voice.reads.whole.content.zip)

**Comment by tonyanziano** [comment] 2019-10-24 18:21
@Kumar2608 @awalia13 

Since this issue was initially reported, we made a change to the Emulator to update the embedded Web Chat control (#1925) which we believe has changed the Voice Over behavior that you originally experienced.

Would it be possible for you to run through this scenario again and update the ticket so that we can proceed fixing the issue with its current behavior?

**Comment by tonyanziano** [comment] 2019-10-30 23:20
@Kumar2608 @awalia13 friendly ping

**Comment by ShikhaMishra11** [comment] 2019-10-31 14:55
As verified in the latest version of Bot Emulator, the issue is fixed now.

So, we are closing the issue.

Verified On: 31/10/2019
OS: MacOs Version 10.15
Application: Bot Framework V4 Emulator (Version 4.5.2-87002)

**Closed** 2019-10-31 17:26 UTC
Labels: A11yCT, A11yLowImpact, A11yMAS, Accessibility, Bug, Emulator-MAC, HCL-BotFrameworkEmulator, InfoRequested, MAS4.2.1, Severity4
