### ISSUE TITLE
Emulator doesn't show suggestion chips correctly

### ISSUE THREAD

**Issue by NiteLordz** [Microsoft/BotFramework-Emulator#487] opened 2018-05-10 17:47 UTC
If you have two response activity messages, both having suggestion chips, only the first set of suggestion chips appears. The second message displays the appropriate text, however, the suggestion chips on the bottom in the bar do not update to the set from the second message.

**Comment by JasonSowers** [comment] 2018-05-11 16:15
Could you please explain what a suggestion chip is?  This isn't a term we use, maybe a screenshot? Could you also please share code to reproduce the issue so we can look into it?

**Comment by NiteLordz** [comment] 2018-05-11 19:14
My apologies.  Suggestion Chip == CardAction.  Messing with too many channels and platforms.

As for screenshots, see attached.

To reproduce, send the two messages from bot to user. Expected to behavior is to have three actions associated with the first message, and then the second message comes in afterward, displaying two actions. However, the second message card actions never display within the emulator. 

IMessageActivites are inside attached file.
[MessageActivities.txt](https://github.com/Microsoft/BotFramework-Emulator/files/1996566/MessageActivities.txt)


Note: Functionality is correct on other channels (Facebook, Skype).
![emulatorv3](https://user-images.githubusercontent.com/2166208/39942508-abbf1608-552d-11e8-9e93-5f810fc37181.png)
![emulatorv4](https://user-images.githubusercontent.com/2166208/39942509-abce59c4-552d-11e8-850d-4ec5f49ba110.png)

**Comment by EricDahlvang** [comment] 2018-05-11 23:37
Hi @NiteLordz,

I think this is by design.  https://github.com/Microsoft/BotFramework-WebChat/blob/e5069bd313c9a61831c994ee5217297e0007375f/src/activityWithSuggestedActions.ts The WebChat, used by the emulator, only renders the last activity's suggested actions.  Do you wish to make a feature request for all suggested actions to be combined? This would need to be done on the WebChat's repository: https://github.com/Microsoft/BotFramework-WebChat/issues/new

**Comment by NiteLordz** [comment] 2018-05-12 01:07
@EricDahlvang 

No, I think that is the bug. I expect that the last message to show the suggested actions. however, if you look at the difference between the two screenshots, EmulatorV3 shows the expected behavior, while EmulatorV4 shows a non-expected behavior. 

As the question for feedback is the last message sent, I would expect the two action buttons (thumbs up/down) to be displayed, however, in EmulatorV4 you can see, that is not the case. The actions that are displayed are from the first message, not the last.

It's like it doesn't update the action bar at the bottom of the emulator.

**Comment by compulim** [comment] 2018-07-02 07:57
Looks like this is fixed in v4 as of commit 85020fd. The screenshot show thumbs up/down buttons from the second card. Not the first card.

![487.png](https://user-images.githubusercontent.com/1622400/42151699-ac4b4a0a-7d92-11e8-9905-f18a1e64d96f.png)

**Closed by compulim** 2018-07-02 07:57 UTC
Labels: bug, v4
