### ISSUE TITLE
Voice not changed using SSML

### ISSUE THREAD

**Issue by YanXuHappygela** [Microsoft/BotFramework-Emulator#260] opened 2017-07-31 21:39 UTC
I have created a bot in node JS using the RollerSkill demo codes and enabled the speech API. I tried to change the voice of bot from a male's voice to a female voice using SSML settings, but it didn't make any changes. Is it a implementation issue or an emulator issue? 

The SSML is the following:
\<speak version="1.0" xml:lang="en-US"\>\<voice name="Microsoft Server Speech Text to Speech Voice (en-US, ZiraRUS)" gender="Female" xml:lang="en-US"\>I'm roller,
the dice rolling bot. You can say 'roll some dice' or play one of the games I know how to play.\</voice\>\</speak\>

**Comment by eanders-MS** [comment] 2017-07-31 21:45
The emulator only passes received messages to the WebChat control, which it its own GitHub project. I think you'll have better luck asking your question over at https://github.com/Microsoft/BotFramework-WebChat/issues

**Comment by nwhitmont** [comment] 2017-08-02 00:56
duplicate of https://github.com/Microsoft/BotBuilder/issues/3231

**Comment by eanders-MS** [comment] 2017-08-03 19:54
This issue does not pertain to the emulator itself, so I will close it.

**Closed by eanders-MS** 2017-08-03 19:54 UTC
