### ISSUE TITLE
Add LUIS resource doesn't recognize I'm the owner of the resource

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Emulator#1497] opened 2019-05-02 00:21 UTC
## Version
4.3.3.57327

## Describe the bug
Add LUIS resource doesn't recognize that I am the owner of the service

## To Reproduce
try to add luis model, you get this
![image](https://user-images.githubusercontent.com/17789481/57051244-814ec380-6c35-11e9-85db-1bc842a70f04.png)

I'm the owner
![image](https://user-images.githubusercontent.com/17789481/57051262-90357600-6c35-11e9-93bf-e51741732c24.png)

## Expected behavior
To let me pick my resources

[bug]

**Comment by stevengum** [comment] 2019-05-17 22:04
For some reason the connection is being closed by the service that provides the programmatic key when authorized with an ARM token:

![unable-to-get-authoring-key](https://user-images.githubusercontent.com/14935595/57958475-d08f2800-78b4-11e9-86b5-a36f894e0fcc.jpg)

Since there is no programmatic key, it's not possible to retrieve any apps so it tells you to try and create a new LUIS app. 

I've reached out to the LUIS team and am awaiting their feedback. The API works just fine; I was able to hit it directly with Postman and successfully retrieved my global authoring key.

**Comment by stevengum** [comment] 2019-06-06 21:09
**Note-to-self:** It would be worth diffing older versions of the Emulator with master as the functionality used to work.

**Comment by cwhitten** [comment] 2019-06-10 18:12
The LUIS teams thinks the request we are sending is malformed.

**Comment by stevengum** [comment] 2019-06-25 21:26
Just checked this today and it works in [4.2.0](https://github.com/microsoft/BotFramework-Emulator/releases/tag/v4.2.0) on Windows. 

The bug is still in `master`, I'm currently looking for the regression.

**Comment by stevengum** [comment] 2019-07-01 21:12
Cross linking **electron/electron#18557** 

Using [`electron-fetch`](https://github.com/arantes555/electron-fetch) doesn't yield any better outcomes compared to the original dependency (using `node-fetch` in [`fetchProxy.ts`](https://github.com/microsoft/BotFramework-Emulator/blob/master/packages/app/main/src/fetchProxy.ts#L36))

**Comment by stevengum** [comment] 2019-07-29 18:18
This seems blocked at the moment because the version of electron now being used in the emulator does not like the LUIS service server (due electron using BoringSSL which is stricter than OpenSSL).

Using the `net` or `electron-fetch` module in electron doesn't remedy the situation as the client (electron main process) still closes the socket.

One way to become unblocked would be to reconfigure the LUIS server, either so it's acceptable by clients using BoringSSL or to allow CORS of some variance (and perform the call from the client).

Another possibility would be to setup a proxy of our own (perhaps using Service Bus) to take ARM token from the emulator and retrieve the LUIS authoring key on behalf of the user.

**Comment by OEvgeny** [comment] 2024-02-28 21:22
Closing as LUIS is on the path of depreciation. If you still find this is the issue we need to fix, please reopen

**Closed by OEvgeny** 2024-02-28 21:22 UTC
Labels: Bug
