### ISSUE TITLE
 Intermittent 500 error with the latest emulator on localhost

### ISSUE THREAD

**Issue by angie4u** [microsoft/BotFramework-Emulator#1664] opened 2019-07-02 09:27 UTC
## Version
4.4.2

## Describe the bug
 I had Intermittent 500 error with the latest emulator(4.4.2) 

## To Reproduce
1. Starting bot at localhost with the latest emulator
2. While doing testing, it will suddenly give you 500 errors.

## Expected behavior
No 500 error if there is no problem with the code.

## Additional context
We used the Virtual Assistant solution(https://github.com/microsoft/botframework-solutions), but I guess it is not the root cause of this problem. It because this issue is resolved by downgrading the version to 4.2.1.

[bug]

**Comment by tonyanziano** [comment] 2019-07-02 20:03
Hi @angie4u ,

Can you provide any more detail or perhaps screenshots about the scenario in which the 500 errors occurred? Were you starting a conversation with the bot, were you in the middle of a conversation with the bot, or did you happen to click an adaptive card button?

It's hard to diagnose a 500 without some more information. Taking a screenshot of the Emulator log panel with the payload of the error would be very helpful.

**Comment by angie4u** [comment] 2019-07-03 01:28
![image](https://user-images.githubusercontent.com/16282358/60556611-280e2800-9d7d-11e9-9f56-1c80adfb4e29.png)

After waiting a few seconds, the bot is starting to work! 
![image](https://user-images.githubusercontent.com/16282358/60556666-58ee5d00-9d7d-11e9-9d5f-5d51f80daa2b.png)

**Comment by angie4u** [comment] 2019-07-03 01:31
It happens during the middle of a conversation intermittently! If you need more information, please let me know!

**Comment by tonyanziano** [comment] 2019-07-03 18:42
I'll try to reproduce with the same sample you used and update this thread.

**Comment by tonyanziano** [comment] 2019-07-17 20:21
Hi @angie4u ,

Please try out your VA bot with the [newest release of the Emulator, 4.5.2](https://github.com/microsoft/BotFramework-Emulator/releases/tag/v4.5.2). The Emulator should now show the error messages you are getting more clearly due to #1673. 

If you are still seeing errors, please take a screenshot of the inspector panel as you did before and post it here. You can also just copy the JSON payload from the inspector panel as well and post it here in a code block:

```
{

  ... some error payload

}
```

**Comment by angie4u** [comment] 2019-07-19 05:50
Hello @tonyanziano,
Thanks for your support! I will test again if the error occurs again, I will post here with screenshots.

**Comment by angie4u** [comment] 2019-07-22 04:14
Hello team,
I still have the same error like below with latest Bot emulator(4.5.2-71403)
![image](https://user-images.githubusercontent.com/16282358/61605876-7af34500-ac82-11e9-92b9-d92378cc544a.png)
![image](https://user-images.githubusercontent.com/16282358/61605889-89d9f780-ac82-11e9-86fc-52cef4c4c686.png)

**Comment by angie4u** [comment] 2019-07-22 05:20
I got this information from Application Insight service. Is this error because of the limitation of ngrok? 
![image](https://user-images.githubusercontent.com/16282358/61607906-c4945d80-ac8b-11e9-9392-4fc6245760f0.png)

**Comment by angie4u** [comment] 2019-07-22 09:43
I found that my ngrok cause the problem. (I use free tier for ngrok https://ngrok.com/pricing) When I test with embedded webchat, it works fine! Thank you for your help!

**Comment by tonyanziano** [comment] 2019-07-22 17:03
Glad to hear you figured it out! Closing this issue now.

**Closed by tonyanziano** 2019-07-22 17:03 UTC
Labels: Bug
